"""
rnpv_config_builder — generate rNPV YAML configs for each target snapshot.

Creates YAML configuration files compatible with bve-asset CLI for each
(target, snapshot_date) combination.  These configs use only data available
at snapshot_date — no post-snapshot information.

Output files are written to:
  research/backtests/vrtx_regn_2010/rnpv_configs/
    <TARGET_TICKER>_<YYYYMMDD>_<DAYS_BEFORE>d.yaml
"""
from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Any, Optional


# Phase label → standard phase key used in bve YAML configs
_PHASE_MAP: dict[str, str] = {
    "phase 1":    "phase_1",
    "phase1":     "phase_1",
    "phase 2":    "phase_2",
    "phase2":     "phase_2",
    "phase 3":    "phase_3",
    "phase3":     "phase_3",
    "nda/bla":    "phase_3",   # treat NDA submission as late phase 3
    "approved":   "approved",
    "preclinical":"phase_1",
}

# Default industry base rates (from bve industry_assumptions.yaml)
_BASE_RATES: dict[str, dict[str, float]] = {
    "rare_disease":         {"phase_1": 0.67, "phase_2": 0.51, "phase_3": 0.80},
    "immunology":           {"phase_1": 0.60, "phase_2": 0.38, "phase_3": 0.70},
    "oncology":             {"phase_1": 0.55, "phase_2": 0.30, "phase_3": 0.58},
    "diabetes_endocrine":   {"phase_1": 0.59, "phase_2": 0.39, "phase_3": 0.67},
    "other":                {"phase_1": 0.60, "phase_2": 0.40, "phase_3": 0.65},
}


class RNPVConfigBuilder:
    """
    Generate rNPV YAML configs for backtest targets.

    All values are from public data as of snapshot_date.
    Missing fields are left as null (not guessed).

    Usage::

        builder = RNPVConfigBuilder()
        yaml_str = builder.build_yaml(
            ticker="ALPN",
            snapshot_date=date(2024, 1, 10),
            target_snap=target_snapshot_dict,
            asset_snap=asset_snapshot_dict,
        )
    """

    def __init__(self, output_dir: Optional["str | Path"] = None) -> None:
        self._output_dir = Path(output_dir) if output_dir else None

    def build_yaml(
        self,
        ticker: str,
        snapshot_date: date,
        days_before: int,
        target_snap: dict[str, Any],
        asset_snap: dict[str, Any],
    ) -> str:
        """
        Return a YAML string for bve-asset compatible with the given snapshot.
        Missing values are written as null with a TODO comment.
        """
        ta = asset_snap.get("therapeutic_area", "other")
        phase_label = asset_snap.get("highest_phase", "preclinical")
        phase_key = _PHASE_MAP.get(phase_label.lower(), "phase_1")
        base_rates = _BASE_RATES.get(ta, _BASE_RATES["other"])

        # rNPV key figures (null if unknown)
        market_cap = target_snap.get("market_cap_millions")
        cash = target_snap.get("cash_millions")

        # Market model: TAM unknown → null; must be filled by researcher
        lines = [
            "# rNPV config generated by RNPVConfigBuilder",
            f"# Ticker: {ticker}",
            f"# Snapshot date: {snapshot_date.isoformat()} ({days_before}d before announcement)",
            f"# Data as of: {asset_snap.get('data_as_of_date', snapshot_date.isoformat())}",
            "# WARNING: All values must be based on data <= snapshot_date.",
            "# MISSING fields marked TODO must be filled from primary sources.",
            "",
            "asset:",
            f"  ticker: {ticker}",
            f"  name: {target_snap.get('lead_asset', 'TODO_asset_name')!r}",
            f"  therapeutic_area: {ta}",
            f"  indication: {asset_snap.get('indication', 'TODO_indication')!r}",
            f"  modality: {asset_snap.get('modality', 'TODO_modality')!r}",
            f"  # highest_phase at snapshot: {phase_label}",
            "",
            "company:",
            f"  ticker: {ticker}",
            "  name: TODO_company_name",
            f"  # market_cap_millions at snapshot: {market_cap or 'NOT_PUBLIC'}",
            f"  # cash_millions at snapshot: {cash or 'UNKNOWN'}",
            "",
            "trials:",
            f"  # Phase at snapshot: {phase_label}",
            f"  - phase: {phase_key}",
            f"    success_probability: {base_rates.get(phase_key, 0.40):.2f}  # industry base rate",
            "    duration_years: null  # TODO: from CT.gov primary completion date",
            "    cost_millions: null   # TODO: from 10-K R&D disclosures",
            "",
            "market_model:",
            f"  total_addressable_market_millions: null  # TODO: analyst/public data as of {snapshot_date.isoformat()}",
            "  peak_penetration: null  # TODO",
            "  years_to_peak: null     # TODO",
            "  patent_life_years: null # TODO",
            "",
            "# NOTE: actual_deal_value is an EVALUATION LABEL only.",
            "# It must not be used as a model input.",
            "# actual_deal_value_millions: LABEL_ONLY",
        ]
        return "\n".join(lines) + "\n"

    def write_config(
        self,
        ticker: str,
        snapshot_date: date,
        days_before: int,
        target_snap: dict[str, Any],
        asset_snap: dict[str, Any],
    ) -> Path:
        """Write the YAML config to disk and return the path."""
        if self._output_dir is None:
            raise ValueError("output_dir must be set to write config files")
        self._output_dir.mkdir(parents=True, exist_ok=True)
        filename = (
            f"{ticker.upper()}_{snapshot_date.strftime('%Y%m%d')}_{days_before}d.yaml"
        )
        path = self._output_dir / filename
        yaml_str = self.build_yaml(ticker, snapshot_date, days_before, target_snap, asset_snap)
        path.write_text(yaml_str, encoding="utf-8")
        return path
