"""
Statistical POS model: logistic regression wrapper around the heuristic adjuster model.

.. warning::
    This module is NOT independently calibrated on real clinical trial outcomes.
    It is a heuristic mirror: the training data is synthetically generated using the
    heuristic model (pos_model.py) as the data-generating process. The logistic
    regression coefficients will therefore approximately match the heuristic log-odds
    adjusters by construction — this is not independent validation.

    ``IS_EMPIRICALLY_CALIBRATED = False``

    Do not present outputs from this module as "statistically calibrated" or
    "independently validated" probabilities. The values are heuristic estimates
    expressed in logistic regression form.

Architecture
------------
The heuristic model (pos_model.py) applies hand-calibrated log-odds adjusters on top of
published base rates. This module re-expresses the same relationship as a logistic
regression. Benefits of this form:

  1. Allows coefficient updates when real outcome data becomes available
  2. Provides a structured path for feature importance inspection
  3. Exposes a comparison function to quantify divergence if coefficients are retrained

Calibration dataset
-------------------
The model is pre-fitted on a 750-program SYNTHETIC dataset. The synthetic generation
uses the heuristic model as the data-generating process; real-program outcome data
(Biomedtracker export, SEC filings, etc.) has NOT been used to fit or validate these
coefficients.

To retrain on real data:
    from bve.models.pos_statistical import retrain_on_csv
    model = retrain_on_csv("path/to/outcomes.csv")

Limitations
-----------
- NOT independently calibrated on real outcomes; mirrors heuristic model by construction.
- Brier score reported by calibration_report() is on TRAINING data only — it measures
  self-consistency, not predictive accuracy.
- Phase 1 programs are excluded (insufficient failure signal in published datasets).
- sample_size_adequacy is not included as a feature (not reliably reported in aggregate data).
"""
from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Optional

import numpy as np
from scipy.optimize import minimize
from scipy.special import expit

from bve.entities.asset import TherapeuticArea
from bve.entities.trial import EndpointType, TrialPhase
from bve.models.pos_model import (
    CompetitivePressure,
    MoAPrecedent,
    POSAdjusters,
    SafetyProfile,
)


# ---------------------------------------------------------------------------
# Calibration status — checked by downstream consumers
# ---------------------------------------------------------------------------

#: Set to True only when real clinical trial outcome data has been used to fit
#: the model coefficients. Currently False: the training set is synthetic,
#: generated by the heuristic model itself.
IS_EMPIRICALLY_CALIBRATED: bool = False


def calibration_status() -> dict:
    """
    Return a machine-readable summary of the model's calibration provenance.

    Returns
    -------
    dict with keys:
        is_empirically_calibrated (bool): False until retrained on real data.
        dataset (str): Description of training data.
        real_programs_n (int): Number of real clinical programs in training set.
        warning (str): Human-readable disclosure.
    """
    return {
        "is_empirically_calibrated": IS_EMPIRICALLY_CALIBRATED,
        "dataset": "synthetic_750_heuristic_dgp",
        "real_programs_n": 0,
        "warning": (
            "Coefficients fitted on synthetic data generated by the heuristic model. "
            "Outputs mirror pos_model.py by construction and are not independently "
            "validated. Brier score in calibration_report() is training-set only."
        ),
    }


# ---------------------------------------------------------------------------
# Published oncology phase transition base rates (Biomedtracker/IQVIA 2021)
# Used as DGP for synthetic calibration data — not adjustable at runtime
# ---------------------------------------------------------------------------

_PHASE_BASE_RATES: dict[str, float] = {
    "phase_2": 0.32,
    "phase_3": 0.55,
    "nda_bla": 0.83,
}

# Mirror of heuristic log-odds adjusters from pos_model.py
# Used only during synthetic data generation — coefficients are then recovered by regression
_H_ENDPOINT: dict[EndpointType, float] = {
    EndpointType.HARD_CLINICAL: +0.35,
    EndpointType.SURROGATE_VALIDATED: 0.00,
    EndpointType.SURROGATE_NOVEL: -0.30,
    EndpointType.BIOMARKER_ONLY: -0.55,
}
_H_MOA: dict[MoAPrecedent, float] = {
    MoAPrecedent.VALIDATED: +0.35,
    MoAPrecedent.PARTIAL: 0.00,
    MoAPrecedent.NOVEL: -0.35,
}
_H_SAFETY: dict[SafetyProfile, float] = {
    SafetyProfile.CLEAN: +0.10,
    SafetyProfile.MINOR: 0.00,
    SafetyProfile.CONCERNING: -0.35,
    SafetyProfile.SERIOUS: -0.80,
}
_H_COMPETITION: dict[CompetitivePressure, float] = {
    CompetitivePressure.LOW: +0.15,
    CompetitivePressure.MODERATE: 0.00,
    CompetitivePressure.HIGH: -0.15,
}
_H_BIOMARKER_BONUS = 0.40


# ---------------------------------------------------------------------------
# Feature encoding
# ---------------------------------------------------------------------------

# Dummy encoding — reference levels are the "average" heuristic defaults:
#   phase_2, surrogate_validated, moa_partial, no_biomarker, safety_minor, competition_moderate
#
# Feature order: [intercept, is_phase3, is_nda,
#                 endpoint_hard, endpoint_novel, endpoint_biomarker,
#                 moa_validated, moa_novel,
#                 biomarker_selected,
#                 safety_clean, safety_concerning, safety_serious,
#                 competition_low, competition_high]

_N_FEATURES = 14


def _encode_features(
    phase: TrialPhase,
    adjusters: POSAdjusters,
) -> np.ndarray:
    """Build the feature vector for a single observation."""
    is_phase3 = 1.0 if phase == TrialPhase.PHASE_3 else 0.0
    is_nda = 1.0 if phase == TrialPhase.NDA_BLA else 0.0

    et = adjusters.endpoint_type
    endpoint_hard = 1.0 if et == EndpointType.HARD_CLINICAL else 0.0
    endpoint_novel = 1.0 if et == EndpointType.SURROGATE_NOVEL else 0.0
    endpoint_biomarker = 1.0 if et == EndpointType.BIOMARKER_ONLY else 0.0

    moa = adjusters.moa_precedent
    moa_validated = 1.0 if moa == MoAPrecedent.VALIDATED else 0.0
    moa_novel = 1.0 if moa == MoAPrecedent.NOVEL else 0.0

    biomarker = 1.0 if adjusters.biomarker_selected_population else 0.0

    sf = adjusters.safety_profile
    safety_clean = 1.0 if sf == SafetyProfile.CLEAN else 0.0
    safety_concerning = 1.0 if sf == SafetyProfile.CONCERNING else 0.0
    safety_serious = 1.0 if sf == SafetyProfile.SERIOUS else 0.0

    cp = adjusters.competitive_pressure
    competition_low = 1.0 if cp == CompetitivePressure.LOW else 0.0
    competition_high = 1.0 if cp == CompetitivePressure.HIGH else 0.0

    return np.array([
        1.0,              # intercept
        is_phase3,
        is_nda,
        endpoint_hard,
        endpoint_novel,
        endpoint_biomarker,
        moa_validated,
        moa_novel,
        biomarker,
        safety_clean,
        safety_concerning,
        safety_serious,
        competition_low,
        competition_high,
    ])


# ---------------------------------------------------------------------------
# Synthetic calibration dataset (generated once at module load)
# ---------------------------------------------------------------------------

def _generate_calibration_dataset(n: int = 750, seed: int = 42) -> tuple[np.ndarray, np.ndarray]:
    """
    Generate a synthetic calibration dataset using the heuristic model as DGP.

    Sampling distribution reflects oncology pipeline composition:
      - Phase mix: 45% Phase 2, 40% Phase 3, 15% NDA (Citeline 2023 pipeline data)
      - Endpoint mix: 15% hard, 60% surrogate_validated, 15% novel, 10% biomarker-only
      - MoA: 30% validated, 45% partial, 25% novel
      - Biomarker enrichment: 35% (elevated for oncology vs all-TA)
      - Safety: 25% clean, 55% minor, 15% concerning, 5% serious
      - Competition: 25% low, 50% moderate, 25% high
    """
    rng = np.random.RandomState(seed)

    _phases = ["phase_2", "phase_3", "nda_bla"]
    _endpoints = list(_H_ENDPOINT.keys())
    _moas = list(_H_MOA.keys())
    _safeties = list(_H_SAFETY.keys())
    _competitions = list(_H_COMPETITION.keys())

    # Use integer indices to avoid numpy string coercion of enum objects
    phases = [_phases[i] for i in rng.choice(len(_phases), size=n, p=[0.45, 0.40, 0.15])]
    endpoint_types = [_endpoints[i] for i in rng.choice(len(_endpoints), size=n, p=[0.15, 0.60, 0.15, 0.10])]
    moa_types = [_moas[i] for i in rng.choice(len(_moas), size=n, p=[0.30, 0.45, 0.25])]
    biomarker_flags = rng.binomial(1, 0.35, size=n)
    safety_types = [_safeties[i] for i in rng.choice(len(_safeties), size=n, p=[0.25, 0.55, 0.15, 0.05])]
    competition_types = [_competitions[i] for i in rng.choice(len(_competitions), size=n, p=[0.25, 0.50, 0.25])]

    X_rows = []
    y_vals = []

    for i in range(n):
        phase_key = phases[i]
        base_rate = _PHASE_BASE_RATES[phase_key]
        base_rate = max(0.01, min(0.99, base_rate))

        # Apply heuristic log-odds to get true P
        log_odds = math.log(base_rate / (1.0 - base_rate))
        log_odds += _H_ENDPOINT[endpoint_types[i]]
        log_odds += _H_MOA[moa_types[i]]
        log_odds += _H_SAFETY[safety_types[i]]
        log_odds += _H_COMPETITION[competition_types[i]]
        if biomarker_flags[i]:
            log_odds += _H_BIOMARKER_BONUS

        heuristic_pos = 1.0 / (1.0 + math.exp(-log_odds))

        # Simulate outcome from true P (adds sampling noise that allows regression to fit)
        outcome = int(rng.binomial(1, heuristic_pos))

        # Build feature vector
        phase_enum = {
            "phase_2": TrialPhase.PHASE_2,
            "phase_3": TrialPhase.PHASE_3,
            "nda_bla": TrialPhase.NDA_BLA,
        }[phase_key]
        adj = POSAdjusters(
            endpoint_type=endpoint_types[i],
            moa_precedent=moa_types[i],
            safety_profile=safety_types[i],
            competitive_pressure=competition_types[i],
            biomarker_selected_population=bool(biomarker_flags[i]),
        )
        X_rows.append(_encode_features(phase_enum, adj))
        y_vals.append(outcome)

    return np.array(X_rows), np.array(y_vals, dtype=float)


def _fit_logistic(X: np.ndarray, y: np.ndarray) -> tuple[np.ndarray, bool]:
    """
    Fit logistic regression by MLE using BFGS optimization.
    Returns (coefficients, converged).
    """
    def neg_log_likelihood(coefs: np.ndarray) -> float:
        p = expit(X @ coefs)
        p = np.clip(p, 1e-12, 1.0 - 1e-12)
        return -float(np.sum(y * np.log(p) + (1.0 - y) * np.log(1.0 - p)))

    def gradient(coefs: np.ndarray) -> np.ndarray:
        p = expit(X @ coefs)
        return X.T @ (p - y)

    result = minimize(
        neg_log_likelihood,
        np.zeros(X.shape[1]),
        jac=gradient,
        method="BFGS",
        options={"maxiter": 1000},
    )
    return result.x, result.success


# Fit once at module load — ~50ms
_CALIB_X, _CALIB_Y = _generate_calibration_dataset(n=750, seed=42)
_COEFS, _FIT_CONVERGED = _fit_logistic(_CALIB_X, _CALIB_Y)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

@dataclass
class StatisticalPOSResult:
    """Output of the statistical POS computation."""
    pos: float
    log_odds: float
    # Feature contributions (feature_name -> log-odds contribution)
    feature_contributions: dict[str, float]


_FEATURE_NAMES = [
    "intercept", "is_phase3", "is_nda",
    "endpoint_hard", "endpoint_novel", "endpoint_biomarker",
    "moa_validated", "moa_novel",
    "biomarker_selected",
    "safety_clean", "safety_concerning", "safety_serious",
    "competition_low", "competition_high",
]


def compute_pos_statistical(
    phase: TrialPhase,
    therapeutic_area: TherapeuticArea,
    adjusters: Optional[POSAdjusters] = None,
) -> float:
    """
    Compute POS using logistic regression (drop-in replacement for compute_pos()).

    .. warning::
        This model is NOT independently calibrated. It is trained on synthetic data
        generated by the heuristic model; outputs mirror pos_model.py by construction.
        Call ``calibration_status()`` to inspect provenance.

    Parameters match compute_pos() exactly for easy comparison.
    therapeutic_area is accepted for API compatibility but is not a feature in the
    current model — the model is calibrated on oncology data; use with caution
    for other TAs.

    Returns
    -------
    float in (0, 1)
    """
    import warnings
    warnings.warn(
        "compute_pos_statistical() uses a heuristic mirror model (IS_EMPIRICALLY_CALIBRATED=False). "
        "Coefficients are fitted on synthetic data generated by pos_model.py — not on real trial outcomes. "
        "Call calibration_status() for details.",
        UserWarning,
        stacklevel=2,
    )
    if adjusters is None:
        adjusters = POSAdjusters()
    if phase == TrialPhase.PHASE_1:
        # Phase 1 not in calibration scope; fall back to base rate
        from bve.config.constants import PHASE_SUCCESS_RATES
        ta_key = therapeutic_area.value
        rates = PHASE_SUCCESS_RATES.get(ta_key) or PHASE_SUCCESS_RATES["all"]
        return rates.get("phase_1", 0.54)

    x = _encode_features(phase, adjusters)
    log_odds = float(x @ _COEFS)
    return round(float(expit(log_odds)), 4)


def compute_pos_statistical_detailed(
    phase: TrialPhase,
    adjusters: Optional[POSAdjusters] = None,
) -> StatisticalPOSResult:
    """Like compute_pos_statistical but returns feature contributions."""
    if adjusters is None:
        adjusters = POSAdjusters()
    x = _encode_features(phase, adjusters)
    contributions = {name: float(x[i] * _COEFS[i]) for i, name in enumerate(_FEATURE_NAMES)}
    log_odds = float(x @ _COEFS)
    return StatisticalPOSResult(
        pos=round(float(expit(log_odds)), 4),
        log_odds=round(log_odds, 4),
        feature_contributions=contributions,
    )


def fitted_coefficients() -> dict[str, float]:
    """Return the fitted logistic regression coefficients."""
    return {name: round(float(_COEFS[i]), 4) for i, name in enumerate(_FEATURE_NAMES)}


@dataclass
class ModelComparison:
    """Comparison of heuristic vs statistical POS estimates."""
    phase: str
    heuristic_pos: float
    statistical_pos: float
    delta: float           # statistical - heuristic
    agree_within_5pp: bool

    def __str__(self) -> str:
        direction = "+" if self.delta >= 0 else ""
        agreement = "agree" if self.agree_within_5pp else "DIVERGE"
        return (
            f"Phase {self.phase}: "
            f"heuristic={self.heuristic_pos:.1%}  "
            f"statistical={self.statistical_pos:.1%}  "
            f"delta={direction}{self.delta:.1%}  [{agreement}]"
        )


def compare_models(
    phase: TrialPhase,
    therapeutic_area: TherapeuticArea,
    adjusters: Optional[POSAdjusters] = None,
) -> ModelComparison:
    """Compare heuristic and statistical POS for the same inputs."""
    from bve.models.pos_model import compute_pos
    h = compute_pos(phase, therapeutic_area, adjusters)
    s = compute_pos_statistical(phase, therapeutic_area, adjusters)
    return ModelComparison(
        phase=phase.value,
        heuristic_pos=h,
        statistical_pos=s,
        delta=round(s - h, 4),
        agree_within_5pp=abs(s - h) < 0.05,
    )


def calibration_report() -> str:
    """
    Report recovered coefficients and compare to expected heuristic log-odds adjusters.
    Use this to verify that the regression is consistent with the heuristic model.
    """
    coefs = fitted_coefficients()

    expected = {
        "intercept": "≈ log-odds of Phase 2 base rate = -0.754",
        "is_phase3": "≈ +0.954 (Phase 3 lift over Phase 2)",
        "is_nda": "≈ +2.336 (NDA lift over Phase 2)",
        "endpoint_hard": "≈ +0.35 (hard clinical endpoint bonus)",
        "endpoint_novel": "≈ -0.30 (novel surrogate penalty)",
        "endpoint_biomarker": "≈ -0.55 (biomarker-only endpoint penalty)",
        "moa_validated": "≈ +0.35 (validated MoA bonus)",
        "moa_novel": "≈ -0.35 (novel MoA penalty)",
        "biomarker_selected": "≈ +0.40 (biomarker-enriched population bonus)",
        "safety_clean": "≈ +0.10 (clean safety bonus)",
        "safety_concerning": "≈ -0.35 (concerning safety penalty)",
        "safety_serious": "≈ -0.80 (serious safety penalty)",
        "competition_low": "≈ +0.15 (low competition bonus)",
        "competition_high": "≈ -0.15 (high competition penalty)",
    }

    lines = [
        "Statistical POS Model — Coefficient Report",
        "  Calibration data: N=750 synthetic programs (seed=42)",
        f"  Optimizer converged: {_FIT_CONVERGED}",
        f"  Calibration Brier score (training): "
        f"{_brier_score(_CALIB_X @ _COEFS, _CALIB_Y):.4f}",
        "",
        f"{'Feature':<22}  {'Fitted':>8}  {'Expected'}",
        "─" * 70,
    ]
    for name in _FEATURE_NAMES:
        fitted = coefs[name]
        exp = expected.get(name, "")
        lines.append(f"  {name:<20}  {fitted:>+8.4f}  {exp}")

    return "\n".join(lines)


def _brier_score(log_odds_vec: np.ndarray, y: np.ndarray) -> float:
    p = expit(log_odds_vec)
    return float(np.mean((p - y) ** 2))


def retrain_on_csv(csv_path: str, outcome_col: str = "outcome", **feature_cols) -> dict[str, float]:
    """
    Retrain the logistic regression on real outcome data from a CSV file.

    The CSV must contain columns matching the feature encoding. Minimal required columns:
      - phase_start: "phase_2" | "phase_3" | "nda_bla"
      - outcome: "approved" | "advanced" (→ success=1) | "failed" (→ success=0)
      - endpoint_type: "hard_clinical" | "surrogate_validated" | "surrogate_novel" | "biomarker_only"
      - moa_precedent: "validated" | "partial" | "novel"
      - biomarker_enriched: "true" | "false"
      - safety_profile: "clean" | "minor" | "concerning" | "serious"
      - competitive_pressure: "low" | "moderate" | "high"

    Returns the new fitted coefficients dict. Does NOT update the module-level _COEFS.
    Call this to evaluate what the model would look like with your real dataset.
    """
    import pandas as pd

    df = pd.read_csv(csv_path)
    required = ["phase_start", outcome_col, "endpoint_type", "moa_precedent",
                 "biomarker_enriched", "safety_profile", "competitive_pressure"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"CSV missing required columns: {missing}")

    phase_map = {
        "phase_2": TrialPhase.PHASE_2,
        "phase_3": TrialPhase.PHASE_3,
        "nda_bla": TrialPhase.NDA_BLA,
    }
    endpoint_map = {e.value: e for e in EndpointType}
    moa_map = {m.value: m for m in MoAPrecedent}
    safety_map = {s.value: s for s in SafetyProfile}
    competition_map = {c.value: c for c in CompetitivePressure}

    X_rows, y_vals = [], []
    for _, row in df.iterrows():
        phase_key = row["phase_start"]
        if phase_key not in phase_map:
            continue
        outcome_val = str(row[outcome_col]).lower()
        if outcome_val == "failed":
            y = 0
        elif outcome_val in ("approved", "advanced"):
            y = 1
        else:
            continue

        adj = POSAdjusters(
            endpoint_type=endpoint_map.get(row.get("endpoint_type", "surrogate_validated"),
                                           EndpointType.SURROGATE_VALIDATED),
            moa_precedent=moa_map.get(row.get("moa_precedent", "partial"), MoAPrecedent.PARTIAL),
            safety_profile=safety_map.get(row.get("safety_profile", "minor"), SafetyProfile.MINOR),
            competitive_pressure=competition_map.get(row.get("competitive_pressure", "moderate"),
                                                     CompetitivePressure.MODERATE),
            biomarker_selected_population=str(row.get("biomarker_enriched", "false")).lower() == "true",
        )
        X_rows.append(_encode_features(phase_map[phase_key], adj))
        y_vals.append(float(y))

    if len(X_rows) < 20:
        raise ValueError(
            f"Only {len(X_rows)} usable rows after filtering. "
            "Need at least 20 (recommend 200+) for stable logistic regression."
        )

    X = np.array(X_rows)
    y = np.array(y_vals)
    coefs, converged = _fit_logistic(X, y)

    result = {name: round(float(coefs[i]), 4) for i, name in enumerate(_FEATURE_NAMES)}
    result["_n_samples"] = len(y_vals)
    result["_converged"] = converged
    result["_brier_score"] = round(_brier_score(X @ coefs, y), 4)
    return result
