"""initial_schema

Revision ID: 7608209898b8
Revises: 
Create Date: 2026-04-18 23:24:10.674011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7608209898b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_type', sa.String(length=50), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('enterprise_value', sa.Float(), nullable=True),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.Column('debt', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index('ix_companies_name', ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_ticker'), ['ticker'], unique=False)

    op.create_table('evidence_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.Column('materiality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum')
    )
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_checksum', ['checksum'], unique=False)
        batch_op.create_index('ix_evidence_source_type', ['source_type'], unique=False)

    op.create_table('parameter_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('promoted', sa.Boolean(), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acquirer_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('strategic_areas', sa.JSON(), nullable=True),
    sa.Column('pipeline_gaps', sa.JSON(), nullable=True),
    sa.Column('loe_cliffs', sa.JSON(), nullable=True),
    sa.Column('bd_preferences', sa.JSON(), nullable=True),
    sa.Column('cash_firepower', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('acquisition_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_company_id', sa.String(length=36), nullable=False),
    sa.Column('acquirer_company_id', sa.String(length=36), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('timing_bucket', sa.String(length=30), nullable=True),
    sa.Column('affordability_score', sa.Float(), nullable=True),
    sa.Column('strategic_fit_score', sa.Float(), nullable=True),
    sa.Column('pipeline_gap_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acquirer_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['target_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_company_id', 'acquirer_company_id', name='uq_acquisition_score')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('modality', sa.String(length=100), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('mechanism', sa.String(length=255), nullable=True),
    sa.Column('therapeutic_area', sa.String(length=100), nullable=True),
    sa.Column('indication', sa.String(length=255), nullable=True),
    sa.Column('current_phase', sa.String(length=50), nullable=True),
    sa.Column('partnered', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', 'indication', name='uq_asset_company_name_indication')
    )
    op.create_table('financing_forecasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('runway_months', sa.Float(), nullable=True),
    sa.Column('pre_catalyst_raise_prob', sa.Float(), nullable=True),
    sa.Column('expected_dilution_low', sa.Float(), nullable=True),
    sa.Column('expected_dilution_high', sa.Float(), nullable=True),
    sa.Column('distress_risk', sa.Float(), nullable=True),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('enterprise_value', sa.Float(), nullable=True),
    sa.Column('iv_event_move', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'as_of', name='uq_market_snapshot_company_asof')
    )
    op.create_table('asset_dossiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('jsonb_state', sa.JSON(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('catalysts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('catalyst_type', sa.String(length=100), nullable=True),
    sa.Column('expected_date', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['evidence_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalysts', schema=None) as batch_op:
        batch_op.create_index('ix_catalysts_asset_date', ['asset_id', 'expected_date'], unique=False)

    op.create_table('competition_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_asset_id', sa.String(length=36), nullable=False),
    sa.Column('target_asset_id', sa.String(length=36), nullable=False),
    sa.Column('edge_type', sa.String(length=50), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_asset_id', 'target_asset_id', 'edge_type', name='uq_competition_edge')
    )
    op.create_table('decision_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('decision_type', sa.String(length=30), nullable=True),
    sa.Column('recommendation', sa.JSON(), nullable=True),
    sa.Column('parameter_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['parameter_version_id'], ['parameter_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('implied_expectations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('market_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('implied_pos', sa.Float(), nullable=True),
    sa.Column('implied_peak_sales', sa.Float(), nullable=True),
    sa.Column('valuation_gap_pct', sa.Float(), nullable=True),
    sa.Column('solver_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['market_snapshot_id'], ['market_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'market_snapshot_id', name='uq_implied_exp_asset_snapshot')
    )
    op.create_table('trials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('nct_id', sa.String(length=20), nullable=True),
    sa.Column('phase', sa.String(length=20), nullable=True),
    sa.Column('endpoint_primary', sa.Text(), nullable=True),
    sa.Column('endpoint_type', sa.String(length=100), nullable=True),
    sa.Column('enrollment_target', sa.Integer(), nullable=True),
    sa.Column('line_of_therapy', sa.String(length=50), nullable=True),
    sa.Column('biomarker_strategy', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('estimated_completion_date', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trials_nct_id'), ['nct_id'], unique=False)

    op.create_table('variant_theses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('market_view', sa.JSON(), nullable=True),
    sa.Column('model_view', sa.JSON(), nullable=True),
    sa.Column('delta_view', sa.JSON(), nullable=True),
    sa.Column('kill_criteria', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('documented', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outcome_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('decision_record_id', sa.String(length=36), nullable=False),
    sa.Column('realized_outcome', sa.JSON(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_record_id'], ['decision_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_record_id')
    )
    op.create_table('scenario_trees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('catalyst_id', sa.String(length=36), nullable=True),
    sa.Column('tree_json', sa.JSON(), nullable=True),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.Column('skew_ratio', sa.Float(), nullable=True),
    sa.Column('setup_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['catalyst_id'], ['catalysts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_trees')
    op.drop_table('outcome_records')
    op.drop_table('variant_theses')
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trials_nct_id'))

    op.drop_table('trials')
    op.drop_table('implied_expectations')
    op.drop_table('decision_records')
    op.drop_table('competition_edges')
    with op.batch_alter_table('catalysts', schema=None) as batch_op:
        batch_op.drop_index('ix_catalysts_asset_date')

    op.drop_table('catalysts')
    op.drop_table('asset_dossiers')
    op.drop_table('market_snapshots')
    op.drop_table('financing_forecasts')
    op.drop_table('assets')
    op.drop_table('acquisition_scores')
    op.drop_table('acquirer_profiles')
    op.drop_table('parameter_versions')
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_source_type')
        batch_op.drop_index('ix_evidence_checksum')

    op.drop_table('evidence_items')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_ticker'))
        batch_op.drop_index('ix_companies_name')

    op.drop_table('companies')
    # ### end Alembic commands ###
