"""Target registry — Oncology and Platform/AI drug discovery companies.

Section A: Oncology (single-asset, platform, ADC, cell therapy, degrader) — 36 companies
Section I: Platform / AI drug discovery — 13 companies

All entries use WatchlistTarget (lightweight; full AcquirableTarget profiles live in
TARGET_UNIVERSE_V2 for the top 10 priority names).

Acquired companies are marked with conviction="acquired" and mna_relevance_score=0.0.
Data confidence reflects quality of public information as of May 2026.
"""
from __future__ import annotations

from bve.entities.target import (
    WatchlistTarget, TargetType, DataConfidence,
)

# ===========================================================================
# Section A — Oncology targets
# ===========================================================================

ONCOLOGY_TARGETS: list[WatchlistTarget] = [

    WatchlistTarget(
        ticker="RVMD", company_id="revolution_medicines", asset_id="a-rvmd",
        company_name="Revolution Medicines",
        indication="RAS-driven cancers (KRAS, NRAS, HRAS, pan-RAS)",
        ranking_score=0.75, opportunity_score=0.68, conviction="medium",
        catalyst="RMC-6236 Phase 3 data readout (PDAC, NSCLC)",
        therapeutic_area="oncology", modality="small_molecule", stage="phase_3",
        lead_asset="RMC-6236 (pan-RAS(ON) inhibitor)",
        market_cap_millions=6_000, cash_millions=1_800,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.80, strategic_scarcity_score=0.88,
        asset_quality_quick_score=0.80, financing_pressure_score=0.25,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="NUVL", company_id="nuvalent", asset_id="a-nuvl",
        company_name="Nuvalent",
        indication="Targeted oncology (ROS1, ALK, EGFR kinase inhibitors)",
        ranking_score=0.72, opportunity_score=0.65, conviction="medium",
        catalyst="NVL-655 (ALK) Phase 2 data; NVL-768 (EGFR) data",
        therapeutic_area="oncology", modality="small_molecule", stage="phase_2",
        lead_asset="zidesamtinib (NVL-520, ROS1)",
        market_cap_millions=4_000, cash_millions=900,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.82, strategic_scarcity_score=0.80,
        asset_quality_quick_score=0.78, financing_pressure_score=0.22,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="SMMT", company_id="summit_therapeutics", asset_id="a-smmt",
        company_name="Summit Therapeutics",
        indication="NSCLC (PD-1/VEGF bispecific); PD-1/VEGF combination oncology",
        ranking_score=0.70, opportunity_score=0.70, conviction="medium",
        catalyst="ivonescimab Phase 3 NSCLC pivotal data vs Keytruda",
        therapeutic_area="oncology", modality="bispecific_antibody", stage="phase_3",
        lead_asset="ivonescimab (AK112, licensed from Akeso)",
        market_cap_millions=5_000, cash_millions=800,
        target_type=TargetType.SINGLE_ASSET, ownership_status="encumbered",
        key_partner="Akeso (licensor, China rights retained)",
        mna_relevance_score=0.78, strategic_scarcity_score=0.82,
        asset_quality_quick_score=0.78, financing_pressure_score=0.28,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="KYMR", company_id="kymera", asset_id="a-kymr",
        company_name="Kymera Therapeutics",
        indication="Degraders: atopic dermatitis, oncology (OX40L, STAT6, IRAK4)",
        ranking_score=0.68, opportunity_score=0.62, conviction="medium",
        catalyst="KY-1005 (OX40L degrader) Phase 2b atopic derm data",
        therapeutic_area="oncology", modality="protein_degrader", stage="phase_2",
        lead_asset="KY-1005 (OX40L PROTAC)",
        market_cap_millions=1_500, cash_millions=700,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="AstraZeneca (IRAK4 degrader partnership)",
        mna_relevance_score=0.72, strategic_scarcity_score=0.78,
        asset_quality_quick_score=0.72, financing_pressure_score=0.28,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="JANX", company_id="janux_therapeutics", asset_id="a-janx",
        company_name="Janux Therapeutics",
        indication="Tumor-activated T cell engagers (PSMA, HER2, EGFR)",
        ranking_score=0.67, opportunity_score=0.60, conviction="medium",
        catalyst="JANX007 (PSMA/CD3) Phase 1/2 data; Pfizer collaboration milestones",
        therapeutic_area="oncology", modality="bispecific_antibody", stage="phase_1",
        lead_asset="JANX007 (PSMA/CD3 TRIDENT bispecific)",
        market_cap_millions=2_000, cash_millions=700,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="Pfizer (JANX007); Merck (JANX008)",
        mna_relevance_score=0.72, strategic_scarcity_score=0.75,
        asset_quality_quick_score=0.70, financing_pressure_score=0.25,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="IOVA", company_id="iovance", asset_id="a-iova",
        company_name="Iovance Biotherapeutics",
        indication="TIL cell therapy: melanoma, cervical, NSCLC",
        ranking_score=0.65, opportunity_score=0.58, conviction="medium",
        catalyst="Amtagvi commercial ramp; cervical cancer approval",
        therapeutic_area="oncology", modality="cell_therapy", stage="approved",
        lead_asset="Amtagvi (lifileucel, first approved TIL therapy)",
        market_cap_millions=1_500, cash_millions=600,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.70, strategic_scarcity_score=0.75,
        asset_quality_quick_score=0.70, financing_pressure_score=0.35,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="XNCR", company_id="xencor", asset_id="a-xncr",
        company_name="Xencor",
        indication="Bispecific antibodies: oncology, autoimmune (XmAb platform)",
        ranking_score=0.62, opportunity_score=0.58, conviction="medium",
        catalyst="vudalimab (PD-1/CTLA-4) Phase 2 data; XmAb819 ADC data",
        therapeutic_area="oncology", modality="bispecific_antibody", stage="phase_2",
        lead_asset="vudalimab (XmAb20717)",
        market_cap_millions=1_200, cash_millions=700,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.70, strategic_scarcity_score=0.72,
        asset_quality_quick_score=0.68, financing_pressure_score=0.22,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ZYME", company_id="zymeworks", asset_id="a-zyme",
        company_name="Zymeworks",
        indication="Bispecific antibodies, ADCs: GI cancers, HER2+",
        ranking_score=0.62, opportunity_score=0.58, conviction="medium",
        catalyst="zanidatamab BTC NDA review; ZW220 (HER3 ADC) Phase 1 data",
        therapeutic_area="oncology", modality="bispecific_antibody", stage="phase_2",
        lead_asset="zanidatamab (HER2 bispecific)",
        market_cap_millions=800, cash_millions=500,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="Jazz Pharma (zanidatamab ex-Asia rights)",
        mna_relevance_score=0.72, strategic_scarcity_score=0.70,
        asset_quality_quick_score=0.68, financing_pressure_score=0.30,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="OLMA", company_id="olema_oncology", asset_id="a-olma",
        company_name="Olema Oncology",
        indication="ER+ breast cancer (next-gen SERD/SERC)",
        ranking_score=0.62, opportunity_score=0.60, conviction="medium",
        catalyst="palazestrant (OP-1250) Phase 3 data vs fulvestrant",
        therapeutic_area="oncology", modality="small_molecule", stage="phase_3",
        lead_asset="palazestrant (OP-1250, SERD/SERC)",
        market_cap_millions=600, cash_millions=250,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.68, strategic_scarcity_score=0.70,
        asset_quality_quick_score=0.68, financing_pressure_score=0.35,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="BCAX", company_id="bicara_therapeutics", asset_id="a-bcax",
        company_name="Bicara Therapeutics",
        indication="Head and neck cancer, NSCLC (EGFR/TGFβ bispecific)",
        ranking_score=0.62, opportunity_score=0.58, conviction="medium",
        catalyst="ficerafusp alfa Phase 2/3 HNSCC data",
        therapeutic_area="oncology", modality="bispecific_antibody", stage="phase_2",
        lead_asset="ficerafusp alfa (anti-EGFR/TGFβ trap fusion)",
        market_cap_millions=1_000, cash_millions=700,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.65, strategic_scarcity_score=0.68,
        asset_quality_quick_score=0.65, financing_pressure_score=0.25,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="CGON", company_id="cg_oncology", asset_id="a-cgon",
        company_name="CG Oncology",
        indication="Bladder cancer (oncolytic adenovirus + checkpoint combination)",
        ranking_score=0.62, opportunity_score=0.55, conviction="medium",
        catalyst="cretostimogene (CG0070) NMIBC Phase 3 approval readout",
        therapeutic_area="oncology", modality="oncolytic_virus", stage="phase_3",
        lead_asset="cretostimogene grenadenorepvec (CG0070)",
        market_cap_millions=1_000, cash_millions=400,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.65, strategic_scarcity_score=0.70,
        asset_quality_quick_score=0.65, financing_pressure_score=0.30,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="NRIX", company_id="nurix", asset_id="a-nrix",
        company_name="Nurix Therapeutics",
        indication="BTK degraders (B-cell malignancies, autoimmune); E3 ligase platform",
        ranking_score=0.62, opportunity_score=0.55, conviction="medium",
        catalyst="NX-5948 (BTK degrader) Phase 1 dose escalation data",
        therapeutic_area="oncology", modality="protein_degrader", stage="phase_1",
        lead_asset="NX-5948 (BTK PROTAC degrader)",
        market_cap_millions=400, cash_millions=200,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="AbbVie (NX-2127 co-development)",
        mna_relevance_score=0.68, strategic_scarcity_score=0.72,
        asset_quality_quick_score=0.65, financing_pressure_score=0.38,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="GLUE", company_id="monte_rosa", asset_id="a-glue",
        company_name="Monte Rosa Therapeutics",
        indication="Molecular glue degraders: Myc-driven cancers, immunology (VAV1)",
        ranking_score=0.60, opportunity_score=0.55, conviction="medium",
        catalyst="MRT-2359 (GSPT1 glue) Phase 1 data; Novartis collaboration",
        therapeutic_area="oncology", modality="molecular_glue", stage="phase_1",
        lead_asset="MRT-2359 (GSPT1 molecular glue)",
        market_cap_millions=500, cash_millions=300,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="Novartis (VAV1 collaboration)",
        mna_relevance_score=0.65, strategic_scarcity_score=0.72,
        asset_quality_quick_score=0.65, financing_pressure_score=0.35,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ADAP", company_id="adaptimmune", asset_id="a-adap",
        company_name="Adaptimmune",
        indication="TCR cell therapy: synovial sarcoma, melanoma, GI cancers",
        ranking_score=0.60, opportunity_score=0.52, conviction="medium",
        catalyst="Tecelra commercial ramp; ADP-A2M4CD8 Phase 2 data",
        therapeutic_area="oncology", modality="cell_therapy", stage="approved",
        lead_asset="Tecelra (afami-cel, first approved TCR therapy for sarcoma)",
        market_cap_millions=300, cash_millions=200,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.65, strategic_scarcity_score=0.70,
        asset_quality_quick_score=0.62, financing_pressure_score=0.45,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="MRSN", company_id="mersana", asset_id="a-mrsn",
        company_name="Mersana Therapeutics",
        indication="ADC platform: NaPi2b, HER2 agonist ADCs",
        ranking_score=0.58, opportunity_score=0.52, conviction="low",
        catalyst="XMT-2056 (HER2 agonist ADC) Phase 1 data; XMT-1592 Phase 1",
        therapeutic_area="oncology", modality="antibody_drug_conjugate", stage="phase_1",
        lead_asset="XMT-1592 (NaPi2b ADC)",
        market_cap_millions=300, cash_millions=200,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.58, financing_pressure_score=0.42,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="STRO", company_id="sutro_biopharma", asset_id="a-stro",
        company_name="Sutro Biopharma",
        indication="ADC platform: FolR1, CD74, CEACAM5 targets",
        ranking_score=0.58, opportunity_score=0.50, conviction="low",
        catalyst="STRO-002 (FolR1 ADC) Phase 2 data",
        therapeutic_area="oncology", modality="antibody_drug_conjugate", stage="phase_2",
        lead_asset="STRO-002 (anti-FolR1 ADC)",
        market_cap_millions=400, cash_millions=200,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.60, strategic_scarcity_score=0.62,
        asset_quality_quick_score=0.58, financing_pressure_score=0.40,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="RPTX", company_id="repare_therapeutics", asset_id="a-rptx",
        company_name="Repare Therapeutics",
        indication="DNA damage response: ATR inhibitor; synthetic lethality",
        ranking_score=0.58, opportunity_score=0.52, conviction="low",
        catalyst="Camonsertib Phase 2 data (BMS co-development)",
        therapeutic_area="oncology", modality="small_molecule", stage="phase_2",
        lead_asset="camonsertib (RP-3500, ATR inhibitor)",
        market_cap_millions=500, cash_millions=200,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="partnered",
        key_partner="Bristol Myers Squibb (camonsertib)",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.60, financing_pressure_score=0.40,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ERAS", company_id="erasca", asset_id="a-eras",
        company_name="Erasca",
        indication="RAS/MAPK oncology: ERK1/2, SHP2 inhibitors",
        ranking_score=0.58, opportunity_score=0.50, conviction="low",
        catalyst="ERAS-007 (ERK1/2) Phase 1/2 combination data",
        therapeutic_area="oncology", modality="small_molecule", stage="phase_1",
        lead_asset="ERAS-007 (ERK1/2 inhibitor)",
        market_cap_millions=300, cash_millions=200,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.58, financing_pressure_score=0.42,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="CGEM", company_id="cullinan_therapeutics", asset_id="a-cgem",
        company_name="Cullinan Therapeutics",
        indication="B-cell malignancies, AML (CLN-978 half-body CD19/CD3; FLT3/CD3)",
        ranking_score=0.58, opportunity_score=0.52, conviction="low",
        catalyst="CLN-978 Phase 1 B-cell malignancy data",
        therapeutic_area="oncology", modality="bispecific_antibody", stage="phase_1",
        lead_asset="CLN-978 (CD19/CD3 half-body)",
        market_cap_millions=500, cash_millions=400,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.62,
        asset_quality_quick_score=0.60, financing_pressure_score=0.30,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="CCCC", company_id="c4_therapeutics", asset_id="a-cccc",
        company_name="C4 Therapeutics",
        indication="IKZF1/3 and BRD9 degraders for hematology/oncology",
        ranking_score=0.55, opportunity_score=0.48, conviction="low",
        catalyst="CFT7455 (IKZF1/3 degrader) Phase 1/2 myeloma data",
        therapeutic_area="oncology", modality="protein_degrader", stage="phase_1",
        lead_asset="CFT7455 (IKZF1/3 PROTAC, with Roche)",
        market_cap_millions=200, cash_millions=150,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="Roche (CFT7455 co-development)",
        mna_relevance_score=0.58, strategic_scarcity_score=0.62,
        asset_quality_quick_score=0.55, financing_pressure_score=0.48,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="PMVP", company_id="pmv_pharma", asset_id="a-pmvp",
        company_name="PMV Pharmaceuticals",
        indication="p53 Y220C reactivation: p53-mutant solid tumors",
        ranking_score=0.55, opportunity_score=0.48, conviction="low",
        catalyst="PC14586 Phase 2 efficacy data",
        therapeutic_area="oncology", modality="small_molecule", stage="phase_2",
        lead_asset="PC14586 (p53 Y220C reactivator)",
        market_cap_millions=200, cash_millions=200,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.60, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.58, financing_pressure_score=0.38,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="MGNX", company_id="macrogenics", asset_id="a-mgnx",
        company_name="MacroGenics",
        indication="B7-H3 ADC, PD-1/LAG-3, MGC018 (B7-H3 ADC)",
        ranking_score=0.55, opportunity_score=0.48, conviction="low",
        catalyst="Vobramitamab duocarmazine (B7-H3 ADC) Phase 2 data",
        therapeutic_area="oncology", modality="antibody_drug_conjugate", stage="phase_2",
        lead_asset="vobramitamab duocarmazine (MGC018, B7-H3 ADC)",
        market_cap_millions=400, cash_millions=200,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.58, strategic_scarcity_score=0.60,
        asset_quality_quick_score=0.55, financing_pressure_score=0.42,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ADCT", company_id="adc_therapeutics", asset_id="a-adct",
        company_name="ADC Therapeutics",
        indication="DLBCL (Zynlonta approved); additional ADC programs",
        ranking_score=0.52, opportunity_score=0.45, conviction="low",
        catalyst="Zynlonta combination label expansion data",
        therapeutic_area="oncology", modality="antibody_drug_conjugate", stage="approved",
        lead_asset="Zynlonta (loncastuximab tesirine, CD19 ADC)",
        market_cap_millions=300, cash_millions=150,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.58, strategic_scarcity_score=0.58,
        asset_quality_quick_score=0.52, financing_pressure_score=0.50,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="FHTX", company_id="foghorn_therapeutics", asset_id="a-fhtx",
        company_name="Foghorn Therapeutics",
        indication="Chromatin regulation: BRG1/BRM inhibitors (oncology)",
        ranking_score=0.52, opportunity_score=0.45, conviction="low",
        catalyst="FHD-286 Phase 1 AML data; Lilly collaboration milestones",
        therapeutic_area="oncology", modality="small_molecule", stage="phase_1",
        lead_asset="FHD-286 (BRG1/BRM inhibitor)",
        market_cap_millions=200, cash_millions=100,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="Eli Lilly (chromatin regulator collaboration)",
        mna_relevance_score=0.55, strategic_scarcity_score=0.60,
        asset_quality_quick_score=0.52, financing_pressure_score=0.50,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="PYXS", company_id="pyxis_oncology", asset_id="a-pyxs",
        company_name="Pyxis Oncology",
        indication="ADC and immunotherapy: LIV-1, Siglec-15",
        ranking_score=0.50, opportunity_score=0.42, conviction="low",
        catalyst="PYX-201 (LIV-1 ADC) Phase 1 data",
        therapeutic_area="oncology", modality="antibody_drug_conjugate", stage="phase_1",
        lead_asset="PYX-201 (LIV-1 ADC)",
        market_cap_millions=200, cash_millions=100,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.55, strategic_scarcity_score=0.58,
        asset_quality_quick_score=0.50, financing_pressure_score=0.52,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="IBRX", company_id="immunitybio", asset_id="a-ibrx",
        company_name="ImmunityBio",
        indication="BCG-unresponsive NMIBC, IL-15 immunotherapy (N-803)",
        ranking_score=0.48, opportunity_score=0.40, conviction="low",
        catalyst="Anktiva commercial ramp in bladder cancer combination",
        therapeutic_area="oncology", modality="biologic", stage="approved",
        lead_asset="Anktiva (N-803, IL-15 receptor superagonist)",
        market_cap_millions=400, cash_millions=100,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.50, strategic_scarcity_score=0.55,
        asset_quality_quick_score=0.48, financing_pressure_score=0.60,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="CTMX", company_id="cytomx", asset_id="a-ctmx",
        company_name="CytomX Therapeutics",
        indication="Tumor-conditional antibodies (Probody platform): EpCAM/CD3",
        ranking_score=0.48, opportunity_score=0.40, conviction="low",
        catalyst="CX-904 (EpCAM/CD3 Probody) Phase 1 solid tumor data",
        therapeutic_area="oncology", modality="bispecific_antibody", stage="phase_1",
        lead_asset="CX-904 (EpCAM/CD3 Probody bispecific)",
        market_cap_millions=200, cash_millions=150,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="Bristol Myers Squibb (Probody collaboration)",
        mna_relevance_score=0.55, strategic_scarcity_score=0.58,
        asset_quality_quick_score=0.48, financing_pressure_score=0.45,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="BDTX", company_id="black_diamond", asset_id="a-bdtx",
        company_name="Black Diamond Therapeutics",
        indication="KRAS G12D, allosteric mutations in oncology",
        ranking_score=0.48, opportunity_score=0.42, conviction="low",
        catalyst="BDTX-4933 (KRAS G12D) Phase 1 data",
        therapeutic_area="oncology", modality="small_molecule", stage="phase_1",
        lead_asset="BDTX-4933 (non-covalent KRAS G12D inhibitor)",
        market_cap_millions=200, cash_millions=200,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.58, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.50, financing_pressure_score=0.38,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="TNGX", company_id="tango_therapeutics", asset_id="a-tngx",
        company_name="Tango Therapeutics",
        indication="Synthetic lethality: TNKS, USP1 inhibitors",
        ranking_score=0.45, opportunity_score=0.40, conviction="low",
        catalyst="TNKS (tankyrase) inhibitor Phase 1 data",
        therapeutic_area="oncology", modality="small_molecule", stage="phase_1",
        lead_asset="TNG260 (TNKS inhibitor)",
        market_cap_millions=300, cash_millions=200,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.55, strategic_scarcity_score=0.60,
        asset_quality_quick_score=0.45, financing_pressure_score=0.48,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="BCAB", company_id="bioatla", asset_id="a-bcab",
        company_name="BioAtla",
        indication="CAB (conditionally active biologics): AXL, ROR2 targets",
        ranking_score=0.45, opportunity_score=0.38, conviction="low",
        catalyst="CAB-AXL-ADC Phase 1/2 data",
        therapeutic_area="oncology", modality="antibody_drug_conjugate", stage="phase_1",
        lead_asset="mecbotamab vedotin (AXL CAB-ADC)",
        market_cap_millions=200, cash_millions=100,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.52, strategic_scarcity_score=0.55,
        asset_quality_quick_score=0.45, financing_pressure_score=0.55,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="BOLD", company_id="boundless_bio", asset_id="a-bold",
        company_name="Boundless Bio",
        indication="ecDNA-dependent oncogene amplification (extrachromosomal DNA)",
        ranking_score=0.45, opportunity_score=0.38, conviction="low",
        catalyst="BBI-355 (ecDNA inhibitor) Phase 1 data",
        therapeutic_area="oncology", modality="small_molecule", stage="phase_1",
        lead_asset="BBI-355 (ecDNA-dependent oncogene inhibitor)",
        market_cap_millions=200, cash_millions=100,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.52, strategic_scarcity_score=0.60,
        asset_quality_quick_score=0.45, financing_pressure_score=0.55,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="AVBP", company_id="arrivent", asset_id="a-avbp",
        company_name="ArriVent BioPharma",
        indication="EGFR-mutant NSCLC (3rd-gen inhibitor from China)",
        ranking_score=0.55, opportunity_score=0.48, conviction="low",
        catalyst="furmonertinib Phase 3 NSCLC data (vs osimertinib)",
        therapeutic_area="oncology", modality="small_molecule", stage="phase_3",
        lead_asset="furmonertinib (EGFR 3rd-gen, licensed from Allist Pharma)",
        market_cap_millions=400, cash_millions=300,
        target_type=TargetType.SINGLE_ASSET, ownership_status="encumbered",
        key_partner="Allist Pharma (China licensor)",
        mna_relevance_score=0.60, strategic_scarcity_score=0.62,
        asset_quality_quick_score=0.58, financing_pressure_score=0.35,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ZNTL", company_id="zentalis", asset_id="a-zntl",
        company_name="Zentalis Pharmaceuticals",
        indication="ER+/HER2- breast cancer (SERD), BCL-2 inhibition",
        ranking_score=0.45, opportunity_score=0.38, conviction="low",
        catalyst="azenosertib (ZN-c3, WEE1 inhibitor) Phase 2 data",
        therapeutic_area="oncology", modality="small_molecule", stage="phase_2",
        lead_asset="azenosertib (ZN-c3, WEE1 inhibitor)",
        market_cap_millions=200, cash_millions=150,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.48, strategic_scarcity_score=0.52,
        asset_quality_quick_score=0.45, financing_pressure_score=0.50,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="KRON", company_id="kronos_bio", asset_id="a-kron",
        company_name="Kronos Bio",
        indication="Oncology transcription factor biology (CDK9, super-enhancers)",
        ranking_score=0.40, opportunity_score=0.35, conviction="very-low",
        catalyst="KB-0742 (CDK9 inhibitor) Phase 1 data",
        therapeutic_area="oncology", modality="small_molecule", stage="phase_1",
        lead_asset="KB-0742 (CDK9 inhibitor)",
        market_cap_millions=150, cash_millions=100,
        target_type=TargetType.DISTRESSED, ownership_status="clean",
        mna_relevance_score=0.42, strategic_scarcity_score=0.48,
        asset_quality_quick_score=0.40, financing_pressure_score=0.65,
        data_confidence=DataConfidence.LOW,
    ),

]

# ===========================================================================
# Section I — Platform / AI drug discovery
# ===========================================================================

PLATFORM_TARGETS: list[WatchlistTarget] = [

    WatchlistTarget(
        ticker="RXRX", company_id="recursion", asset_id="a-rxrx",
        company_name="Recursion Pharmaceuticals",
        indication="AI-enabled drug discovery platform (multiple TAs)",
        ranking_score=0.60, opportunity_score=0.55, conviction="medium",
        catalyst="REC-994 (CCM) Phase 2 data; NVIDIA partnership milestones",
        therapeutic_area="platform", modality="ai_drug_discovery", stage="phase_2",
        lead_asset="REC-994 (cerebral cavernous malformation)",
        market_cap_millions=2_000, cash_millions=600,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.65, strategic_scarcity_score=0.70,
        asset_quality_quick_score=0.60, financing_pressure_score=0.35,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="SDGR", company_id="schrodinger", asset_id="a-sdgr",
        company_name="Schrödinger",
        indication="Computational chemistry platform + clinical programs (MALT1, CDC7)",
        ranking_score=0.58, opportunity_score=0.52, conviction="medium",
        catalyst="SGR-1505 (MALT1) Phase 1/2 data",
        therapeutic_area="platform", modality="computational_chemistry", stage="phase_1",
        lead_asset="SGR-1505 (MALT1 inhibitor)",
        market_cap_millions=1_500, cash_millions=600,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.68,
        asset_quality_quick_score=0.60, financing_pressure_score=0.32,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ABSI", company_id="absci", asset_id="a-absi",
        company_name="Absci Corporation",
        indication="AI-designed biologics discovery platform",
        ranking_score=0.50, opportunity_score=0.45, conviction="low",
        catalyst="AI biologics platform partnerships; first in-house program",
        therapeutic_area="platform", modality="ai_biologics", stage="phase_1",
        lead_asset="ABS-101 (undisclosed target, AI-designed antibody)",
        market_cap_millions=300, cash_millions=200,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.55, strategic_scarcity_score=0.60,
        asset_quality_quick_score=0.48, financing_pressure_score=0.42,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="DNA", company_id="ginkgo_bioworks", asset_id="a-dna",
        company_name="Ginkgo Bioworks",
        indication="Synthetic biology platform: biosecurity, fermentation, cell programming",
        ranking_score=0.45, opportunity_score=0.38, conviction="low",
        catalyst="Biosecurity revenue; new cell programming partnerships",
        therapeutic_area="platform", modality="synthetic_biology", stage="phase_1",
        lead_asset="Ginkgo cell programming platform",
        market_cap_millions=700, cash_millions=500,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.48, strategic_scarcity_score=0.55,
        asset_quality_quick_score=0.45, financing_pressure_score=0.45,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="TWST", company_id="twist_bioscience", asset_id="a-twst",
        company_name="Twist Bioscience",
        indication="Synthetic DNA tools: antibody libraries, gene synthesis, NGS",
        ranking_score=0.48, opportunity_score=0.42, conviction="low",
        catalyst="Antibody discovery revenue ramp; data storage milestones",
        therapeutic_area="platform", modality="synthetic_dna", stage="phase_1",
        lead_asset="Twist synthetic DNA platform + antibody library",
        market_cap_millions=600, cash_millions=300,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.52, strategic_scarcity_score=0.58,
        asset_quality_quick_score=0.48, financing_pressure_score=0.40,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="TXG", company_id="10x_genomics", asset_id="a-txg",
        company_name="10x Genomics",
        indication="Single-cell and spatial genomics tools (Chromium, Visium, Xenium)",
        ranking_score=0.55, opportunity_score=0.48, conviction="low",
        catalyst="Chromium X revenue; Xenium spatial adoption; new assay launches",
        therapeutic_area="platform", modality="single_cell_tools", stage="approved",
        lead_asset="Chromium + Visium + Xenium spatial transcriptomics",
        market_cap_millions=1_500, cash_millions=400,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.58, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.55, financing_pressure_score=0.35,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="PACB", company_id="pacific_biosciences", asset_id="a-pacb",
        company_name="Pacific Biosciences",
        indication="Long-read DNA sequencing platform (Revio, Onso)",
        ranking_score=0.50, opportunity_score=0.42, conviction="low",
        catalyst="Revio instrument adoption; Onso short-read launch",
        therapeutic_area="platform", modality="sequencing", stage="approved",
        lead_asset="Revio long-read sequencer",
        market_cap_millions=500, cash_millions=300,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.55, strategic_scarcity_score=0.60,
        asset_quality_quick_score=0.50, financing_pressure_score=0.45,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="NAUT", company_id="nautilus_bio", asset_id="a-naut",
        company_name="Nautilus Biotechnology",
        indication="Single-molecule protein sequencing and proteomics platform",
        ranking_score=0.45, opportunity_score=0.38, conviction="low",
        catalyst="First commercial proteomics instrument launch",
        therapeutic_area="platform", modality="proteomics", stage="phase_1",
        lead_asset="Nautilus single-molecule protein sequencing platform",
        market_cap_millions=300, cash_millions=200,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.50, strategic_scarcity_score=0.58,
        asset_quality_quick_score=0.45, financing_pressure_score=0.42,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="ADPT", company_id="adaptive_biotechnologies", asset_id="a-adpt",
        company_name="Adaptive Biotechnologies",
        indication="Immune profiling platform: MRD testing (clonoSEQ), T-cell mapping",
        ranking_score=0.52, opportunity_score=0.45, conviction="low",
        catalyst="clonoSEQ MRD volume growth; pairSEQ drug discovery partnerships",
        therapeutic_area="platform", modality="immune_profiling", stage="approved",
        lead_asset="clonoSEQ (MRD detection, FDA-cleared)",
        market_cap_millions=500, cash_millions=300,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.58, strategic_scarcity_score=0.62,
        asset_quality_quick_score=0.52, financing_pressure_score=0.38,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="CDXS", company_id="codexis", asset_id="a-cdxs",
        company_name="Codexis",
        indication="Enzyme engineering platform for pharma manufacturing and diagnostics",
        ranking_score=0.45, opportunity_score=0.38, conviction="low",
        catalyst="CodeEvolver licensing revenue; manufacturing enzyme deals",
        therapeutic_area="platform", modality="enzyme_engineering", stage="approved",
        lead_asset="CodeEvolver platform (Pfizer partnership for sitagliptin synthesis)",
        market_cap_millions=200, cash_millions=100,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.48, strategic_scarcity_score=0.55,
        asset_quality_quick_score=0.45, financing_pressure_score=0.55,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="GRTS", company_id="gritstone_bio", asset_id="a-grts",
        company_name="Gritstone bio",
        indication="Personalized neoantigen cancer vaccines + mRNA self-amplifying immunotherapy",
        ranking_score=0.48, opportunity_score=0.40, conviction="low",
        catalyst="SLATE-3 NSCLC Phase 2 data; saRNA platform partnerships",
        therapeutic_area="oncology", modality="mrna_vaccine", stage="phase_2",
        lead_asset="GRANITE (personalized neoantigen vaccine) + SLATE pan-cancer",
        market_cap_millions=200, cash_millions=100,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.52, strategic_scarcity_score=0.58,
        asset_quality_quick_score=0.48, financing_pressure_score=0.55,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="SEER", company_id="seer_bio", asset_id="a-seer",
        company_name="Seer",
        indication="Proteomics discovery platform (Proteograph XT)",
        ranking_score=0.42, opportunity_score=0.35, conviction="very-low",
        catalyst="Proteograph XT commercial adoption; biopharma partnerships",
        therapeutic_area="platform", modality="proteomics", stage="approved",
        lead_asset="Proteograph XT (nanoparticle-based proteomics)",
        market_cap_millions=200, cash_millions=150,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.45, strategic_scarcity_score=0.52,
        asset_quality_quick_score=0.42, financing_pressure_score=0.50,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="QSI", company_id="quantum_si", asset_id="a-qsi",
        company_name="Quantum-Si",
        indication="Semiconductor-based protein sequencing (Platinum instrument)",
        ranking_score=0.40, opportunity_score=0.32, conviction="very-low",
        catalyst="Platinum instrument commercial launch; proteomic service revenue",
        therapeutic_area="platform", modality="protein_sequencing", stage="approved",
        lead_asset="Platinum (semiconductor protein sequencer)",
        market_cap_millions=150, cash_millions=100,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.42, strategic_scarcity_score=0.50,
        asset_quality_quick_score=0.40, financing_pressure_score=0.55,
        data_confidence=DataConfidence.LOW,
    ),
]

# Combined for registry import
ONCOLOGY_AND_PLATFORM_TARGETS: list[WatchlistTarget] = (
    ONCOLOGY_TARGETS + PLATFORM_TARGETS
)
