"""Target registry — Immunology, Rare Disease / Genetic Medicines, CNS.

Section B: Immunology / inflammation — 13 companies
Section C: Rare disease / genetic medicines — 19 companies
Section D: Neuroscience / CNS — 13 companies

All entries use WatchlistTarget. Note: Calliditas acquired by AstraZeneca 2024;
Avidity acquired by Novartis 2026 — both moved to precedent.
"""
from __future__ import annotations

from bve.entities.target import (
    WatchlistTarget, TargetType, DataConfidence,
)

# ===========================================================================
# Section B — Immunology / inflammation
# ===========================================================================

IMMUNOLOGY_TARGETS: list[WatchlistTarget] = [

    WatchlistTarget(
        ticker="MLTX", company_id="moonlake", asset_id="a-mltx",
        company_name="MoonLake Immunotherapeutics",
        indication="Psoriatic arthritis, hidradenitis suppurativa, plaque psoriasis",
        ranking_score=0.75, opportunity_score=0.70, conviction="medium",
        catalyst="Sonelokimab Phase 3 HS (LARIMAR) and PsA data readouts",
        therapeutic_area="immunology", modality="nanobody", stage="phase_3",
        lead_asset="sonelokimab (anti-IL-17A/F nanobody)",
        market_cap_millions=2_000, cash_millions=500,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.82, strategic_scarcity_score=0.85,
        asset_quality_quick_score=0.80, financing_pressure_score=0.28,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="SYRE", company_id="spyre_therapeutics", asset_id="a-syre",
        company_name="Spyre Therapeutics",
        indication="IBD: Crohn's disease, ulcerative colitis (TL1A/IL-23, α4β7/FcRn bispecifics)",
        ranking_score=0.70, opportunity_score=0.65, conviction="medium",
        catalyst="SPY002 (TL1A/IL-23 bispecific) Phase 2 Crohn's data",
        therapeutic_area="immunology", modality="bispecific_antibody", stage="phase_2",
        lead_asset="SPY002 (TL1A/IL-23 bispecific)",
        market_cap_millions=1_000, cash_millions=500,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.78, strategic_scarcity_score=0.80,
        asset_quality_quick_score=0.72, financing_pressure_score=0.28,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="VERA", company_id="vera_therapeutics", asset_id="a-vera",
        company_name="Vera Therapeutics",
        indication="IgA nephropathy, lupus nephritis (BAFF/APRIL dual targeting)",
        ranking_score=0.68, opportunity_score=0.65, conviction="medium",
        catalyst="Atacicept Phase 3 IgAN (ORIGIN-3) pivotal data",
        therapeutic_area="immunology", modality="fusion_protein", stage="phase_3",
        lead_asset="atacicept (TACI-Fc, anti-BAFF/APRIL)",
        market_cap_millions=1_500, cash_millions=500,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.75, strategic_scarcity_score=0.78,
        asset_quality_quick_score=0.75, financing_pressure_score=0.28,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ALMS", company_id="alumis", asset_id="a-alms",
        company_name="Alumis",
        indication="Psoriasis, SLE, MS (selective oral TYK2 inhibitor)",
        ranking_score=0.65, opportunity_score=0.60, conviction="medium",
        catalyst="ESK-001 (TYK2 inhibitor) Phase 3 plaque psoriasis data",
        therapeutic_area="immunology", modality="small_molecule", stage="phase_3",
        lead_asset="ESK-001 (oral selective TYK2 inhibitor)",
        market_cap_millions=800, cash_millions=300,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.72, strategic_scarcity_score=0.72,
        asset_quality_quick_score=0.68, financing_pressure_score=0.32,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ANAB", company_id="anaptysbio", asset_id="a-anab",
        company_name="AnaptysBio",
        indication="Atopic dermatitis, prurigo nodularis (BTLA agonist, PD-1 agonist)",
        ranking_score=0.62, opportunity_score=0.58, conviction="medium",
        catalyst="Rosnilimab (PD-1 agonist) Phase 2b atopic derm data",
        therapeutic_area="immunology", modality="monoclonal_antibody", stage="phase_2",
        lead_asset="rosnilimab (anti-PD-1 agonist)",
        market_cap_millions=800, cash_millions=400,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.68, strategic_scarcity_score=0.70,
        asset_quality_quick_score=0.65, financing_pressure_score=0.30,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="CABA", company_id="cabaletta_bio", asset_id="a-caba",
        company_name="Cabaletta Bio",
        indication="B-cell driven autoimmune disease (anti-CD19 CAR-T, myasthenia gravis, lupus)",
        ranking_score=0.62, opportunity_score=0.58, conviction="medium",
        catalyst="CABA-201 Phase 1/2 data in MG and SLE",
        therapeutic_area="immunology", modality="cell_therapy", stage="phase_1",
        lead_asset="CABA-201 (anti-CD19 CAR-T for autoimmune)",
        market_cap_millions=400, cash_millions=300,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.70, strategic_scarcity_score=0.72,
        asset_quality_quick_score=0.62, financing_pressure_score=0.32,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="RNAC", company_id="cartesian_therapeutics", asset_id="a-rnac",
        company_name="Cartesian Therapeutics",
        indication="Myasthenia gravis and B-cell autoimmune (RNA-engineered T cells)",
        ranking_score=0.62, opportunity_score=0.58, conviction="medium",
        catalyst="Descartes-08 Phase 2/3 MG data (AMEERA-3)",
        therapeutic_area="immunology", modality="cell_therapy", stage="phase_2",
        lead_asset="descartes-08 (RNA-engineered BCMA CAR-T for MG)",
        market_cap_millions=600, cash_millions=300,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.70, strategic_scarcity_score=0.72,
        asset_quality_quick_score=0.62, financing_pressure_score=0.35,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ABVX", company_id="abivax", asset_id="a-abvx",
        company_name="Abivax",
        indication="Ulcerative colitis, RA (obefazimod — RNA regulatory mechanism)",
        ranking_score=0.60, opportunity_score=0.55, conviction="medium",
        catalyst="obefazimod Phase 3 UC (ABTECT) primary endpoint data",
        therapeutic_area="immunology", modality="small_molecule", stage="phase_3",
        lead_asset="obefazimod (ABX464, once-daily oral UC)",
        market_cap_millions=500, cash_millions=200,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.65, strategic_scarcity_score=0.68,
        asset_quality_quick_score=0.62, financing_pressure_score=0.38,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="TRML", company_id="tourmaline_bio", asset_id="a-trml",
        company_name="Tourmaline Bio",
        indication="IBD, HS (anti-LIGHT/TNFSF14 antibody)",
        ranking_score=0.58, opportunity_score=0.52, conviction="low",
        catalyst="pacibekitug Phase 2 IBD and HS data",
        therapeutic_area="immunology", modality="monoclonal_antibody", stage="phase_2",
        lead_asset="pacibekitug (izokibep / anti-LIGHT)",
        market_cap_millions=500, cash_millions=300,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.58, financing_pressure_score=0.35,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="VTYX", company_id="ventyx_biosciences", asset_id="a-vtyx",
        company_name="Ventyx Biosciences",
        indication="IBD, SLE (S1P1 agonist, TYK2 inhibitor)",
        ranking_score=0.55, opportunity_score=0.48, conviction="low",
        catalyst="VTX002 (S1P1 agonist) Phase 2 UC data",
        therapeutic_area="immunology", modality="small_molecule", stage="phase_2",
        lead_asset="VTX002 (selective S1P1 agonist for IBD)",
        market_cap_millions=400, cash_millions=300,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.58, financing_pressure_score=0.32,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="IMUX", company_id="immunic", asset_id="a-imux",
        company_name="Immunic",
        indication="Autoimmune/neuroinflammatory (DHODH inhibitor)",
        ranking_score=0.40, opportunity_score=0.32, conviction="very-low",
        catalyst="Vidofludimus calcium Phase 3 MS data",
        therapeutic_area="immunology", modality="small_molecule", stage="phase_3",
        lead_asset="vidofludimus calcium (IMU-838, DHODH inhibitor)",
        market_cap_millions=150, cash_millions=50,
        target_type=TargetType.DISTRESSED, ownership_status="clean",
        mna_relevance_score=0.40, strategic_scarcity_score=0.45,
        asset_quality_quick_score=0.40, financing_pressure_score=0.70,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="RAPT", company_id="rapt_therapeutics", asset_id="a-rapt",
        company_name="RAPT Therapeutics",
        indication="Atopic dermatitis, eosinophilic esophagitis (CCR4 antagonist)",
        ranking_score=0.38, opportunity_score=0.30, conviction="very-low",
        catalyst="FLX475 (CCR4 antagonist) Phase 2 atopic derm data",
        therapeutic_area="immunology", modality="small_molecule", stage="phase_2",
        lead_asset="FLX475 (oral CCR4 antagonist)",
        market_cap_millions=100, cash_millions=50,
        target_type=TargetType.DISTRESSED, ownership_status="clean",
        mna_relevance_score=0.38, strategic_scarcity_score=0.42,
        asset_quality_quick_score=0.38, financing_pressure_score=0.75,
        data_confidence=DataConfidence.LOW,
    ),

]
# Note: Structure Therapeutics (GPCR) is in CARDIOMETABOLIC_TARGETS (target_registry_other.py)

# ===========================================================================
# Section C — Rare disease / genetic medicines
# ===========================================================================

RARE_DISEASE_TARGETS: list[WatchlistTarget] = [

    WatchlistTarget(
        ticker="BEAM", company_id="beam_therapeutics", asset_id="a-beam",
        company_name="Beam Therapeutics",
        indication="Sickle cell disease, beta-thalassemia, GSD1a (base editing)",
        ranking_score=0.70, opportunity_score=0.65, conviction="medium",
        catalyst="BEAM-101 SCD Phase 2 data; BEAM-302 (alpha-1 antitrypsin) data",
        therapeutic_area="rare_disease", modality="base_editing", stage="phase_1",
        lead_asset="BEAM-101 (SCD base editing)",
        market_cap_millions=2_000, cash_millions=800,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.78, strategic_scarcity_score=0.82,
        asset_quality_quick_score=0.72, financing_pressure_score=0.28,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="NTLA", company_id="intellia", asset_id="a-ntla",
        company_name="Intellia Therapeutics",
        indication="ATTR amyloidosis, HAE, hemophilia A/B (CRISPR in vivo editing)",
        ranking_score=0.68, opportunity_score=0.62, conviction="medium",
        catalyst="NTLA-2001 (ATTR) Phase 3 data; NTLA-2002 (HAE) Phase 2/3 data",
        therapeutic_area="rare_disease", modality="crispr_gene_editing", stage="phase_3",
        lead_asset="nexiguran ziclumeran (NTLA-2001, transthyretin knockdown)",
        market_cap_millions=1_500, cash_millions=500,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="Novartis (OTC disorders), Regeneron (ex-liver programs)",
        mna_relevance_score=0.75, strategic_scarcity_score=0.80,
        asset_quality_quick_score=0.72, financing_pressure_score=0.32,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="CRSP", company_id="crispr_therapeutics", asset_id="a-crsp",
        company_name="CRISPR Therapeutics",
        indication="SCD/TDT (Casgevy approved), allogeneic CAR-T, type 1 diabetes",
        ranking_score=0.68, opportunity_score=0.62, conviction="medium",
        catalyst="Casgevy commercial ramp; CTX112 (allogeneic CAR-T) Phase 1 data",
        therapeutic_area="rare_disease", modality="crispr_gene_editing", stage="approved",
        lead_asset="Casgevy (exagamglogene autotemcel, with Vertex)",
        market_cap_millions=3_000, cash_millions=2_000,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="Vertex Pharmaceuticals (Casgevy co-development)",
        mna_relevance_score=0.75, strategic_scarcity_score=0.80,
        asset_quality_quick_score=0.72, financing_pressure_score=0.22,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="DYN", company_id="dyne_therapeutics", asset_id="a-dyn",
        company_name="Dyne Therapeutics",
        indication="Muscle diseases: DM1 (myotonic dystrophy), DMD exon skipping",
        ranking_score=0.65, opportunity_score=0.60, conviction="medium",
        catalyst="DYNE-101 Phase 2 DM1 data; DYNE-251 Phase 1/2 DMD data",
        therapeutic_area="rare_disease", modality="oligonucleotide", stage="phase_2",
        lead_asset="DYNE-101 (anti-DMPK for DM1)",
        market_cap_millions=1_000, cash_millions=500,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.72, strategic_scarcity_score=0.75,
        asset_quality_quick_score=0.68, financing_pressure_score=0.30,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="RARE", company_id="ultragenyx", asset_id="a-rare",
        company_name="Ultragenyx Pharmaceutical",
        indication="Multiple rare diseases: XLH, CDG, GSD, MMA (commercial franchise)",
        ranking_score=0.62, opportunity_score=0.55, conviction="medium",
        catalyst="Dojolvi/Crysvita commercial; gene therapy programs (DTX401 GSD Ia)",
        therapeutic_area="rare_disease", modality="biologic", stage="approved",
        lead_asset="Crysvita (burosumab, XLH) + Dojolvi + gene therapy pipeline",
        market_cap_millions=2_500, cash_millions=600,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="partnered",
        key_partner="Kyowa Kirin (burosumab co-develop)",
        mna_relevance_score=0.68, strategic_scarcity_score=0.70,
        asset_quality_quick_score=0.65, financing_pressure_score=0.32,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="XENE", company_id="xenon_pharma", asset_id="a-xene",
        company_name="Xenon Pharmaceuticals",
        indication="Epilepsy, rare sodium channelopathies (Nav channel modulation)",
        ranking_score=0.65, opportunity_score=0.62, conviction="medium",
        catalyst="azetukalner (XEN1101) Phase 3 focal epilepsy data (XENLETA)",
        therapeutic_area="rare_disease", modality="small_molecule", stage="phase_3",
        lead_asset="azetukalner (XEN1101, Kv7 potassium channel opener) — partnered Neurocrine",
        market_cap_millions=2_000, cash_millions=600,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="partnered",
        key_partner="Neurocrine Biosciences (azetukalner global partnership)",
        mna_relevance_score=0.72, strategic_scarcity_score=0.75,
        asset_quality_quick_score=0.72, financing_pressure_score=0.25,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="RGNX", company_id="regenxbio", asset_id="a-rgnx",
        company_name="REGENXBIO",
        indication="AAV gene therapy: Hunter syndrome, DMD, wet AMD, retinal",
        ranking_score=0.60, opportunity_score=0.55, conviction="medium",
        catalyst="RGX-121 (Hunter syndrome) BLA; RGX-202 (DMD) Phase 1/2 data",
        therapeutic_area="rare_disease", modality="gene_therapy", stage="phase_2",
        lead_asset="RGX-121 (AAV9 for Hunter syndrome/MPS II)",
        market_cap_millions=800, cash_millions=400,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="AbbVie (RGX-314 wet AMD collaboration)",
        mna_relevance_score=0.65, strategic_scarcity_score=0.68,
        asset_quality_quick_score=0.62, financing_pressure_score=0.38,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="FDMT", company_id="4d_molecular", asset_id="a-fdmt",
        company_name="4D Molecular Therapeutics",
        indication="Ocular gene therapy (4D-150 wet AMD/DR), Fabry disease",
        ranking_score=0.60, opportunity_score=0.58, conviction="medium",
        catalyst="4D-150 intravitreal wet AMD Phase 2b/3 data",
        therapeutic_area="rare_disease", modality="gene_therapy", stage="phase_2",
        lead_asset="4D-150 (intravitreal AAV for wet AMD/DR)",
        market_cap_millions=500, cash_millions=250,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.68, strategic_scarcity_score=0.70,
        asset_quality_quick_score=0.65, financing_pressure_score=0.38,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="PRME", company_id="prime_medicine", asset_id="a-prme",
        company_name="Prime Medicine",
        indication="CGD, Wilson disease, Pompe disease (prime editing)",
        ranking_score=0.58, opportunity_score=0.52, conviction="medium",
        catalyst="PM359 (chronic granulomatous disease) Phase 1 IND clearance and data",
        therapeutic_area="rare_disease", modality="prime_editing", stage="phase_1",
        lead_asset="PM359 (prime editing for X-linked CGD)",
        market_cap_millions=600, cash_millions=300,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.68, strategic_scarcity_score=0.72,
        asset_quality_quick_score=0.60, financing_pressure_score=0.35,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="STOK", company_id="stoke_therapeutics", asset_id="a-stok",
        company_name="Stoke Therapeutics",
        indication="Dravet syndrome, SYNGAP1-related intellectual disability (RNA upregulation)",
        ranking_score=0.58, opportunity_score=0.52, conviction="medium",
        catalyst="STK-001 (zorevunersen) Phase 2/3 Dravet data",
        therapeutic_area="rare_disease", modality="antisense", stage="phase_2",
        lead_asset="STK-001 (zorevunersen, antisense for SCN1A haploinsufficiency)",
        market_cap_millions=400, cash_millions=200,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.65, strategic_scarcity_score=0.68,
        asset_quality_quick_score=0.62, financing_pressure_score=0.40,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="QURE", company_id="uniqure", asset_id="a-qure",
        company_name="uniQure",
        indication="Hemophilia B (Hemgenix approved); Huntington's disease gene therapy",
        ranking_score=0.58, opportunity_score=0.50, conviction="medium",
        catalyst="AMT-130 (Huntington's) Phase 1/2 biomarker data",
        therapeutic_area="rare_disease", modality="gene_therapy", stage="approved",
        lead_asset="etranacogene dezaparvovec (Hemgenix, with CSL Behring)",
        market_cap_millions=700, cash_millions=300,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="partnered",
        key_partner="CSL Behring (Hemgenix commercialization)",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.60, financing_pressure_score=0.40,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="TRDA", company_id="entrada_therapeutics", asset_id="a-trda",
        company_name="Entrada Therapeutics",
        indication="DMD, DM1 (LEAPTIDE intracellular delivery platform)",
        ranking_score=0.58, opportunity_score=0.50, conviction="low",
        catalyst="ENTR-601-44 (DMD exon 44 skip) Phase 1/2 data",
        therapeutic_area="rare_disease", modality="oligonucleotide", stage="phase_1",
        lead_asset="ENTR-601-44 (DMD exon 44 skipping)",
        market_cap_millions=400, cash_millions=200,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.58, financing_pressure_score=0.42,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="PEPG", company_id="pepgen", asset_id="a-pepg",
        company_name="PepGen",
        indication="DMD, DM1 (PEPGEN enhanced delivery oligonucleotides)",
        ranking_score=0.55, opportunity_score=0.48, conviction="low",
        catalyst="PGN-EDODM1 Phase 1 DM1 data",
        therapeutic_area="rare_disease", modality="oligonucleotide", stage="phase_1",
        lead_asset="PGN-EDODM1 (myotonic dystrophy type 1)",
        market_cap_millions=300, cash_millions=150,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.60, strategic_scarcity_score=0.62,
        asset_quality_quick_score=0.55, financing_pressure_score=0.45,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="MGTX", company_id="meiragtx", asset_id="a-mgtx",
        company_name="MeiraGTx",
        indication="Retinal gene therapy (XLRS, achromatopsia, arRP), salivary gland, CNS",
        ranking_score=0.55, opportunity_score=0.48, conviction="low",
        catalyst="AAV-RPGR (arRP) Phase 2/3 data; salivary gland Phase 1",
        therapeutic_area="rare_disease", modality="gene_therapy", stage="phase_2",
        lead_asset="AAV-RPGR (X-linked retinitis pigmentosa)",
        market_cap_millions=400, cash_millions=150,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.58, strategic_scarcity_score=0.60,
        asset_quality_quick_score=0.55, financing_pressure_score=0.48,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="SLDB", company_id="solid_biosciences", asset_id="a-sldb",
        company_name="Solid Biosciences",
        indication="Duchenne muscular dystrophy (AAV9 micro-dystrophin gene therapy)",
        ranking_score=0.48, opportunity_score=0.42, conviction="low",
        catalyst="SGT-003 Phase 1/2 DMD efficacy data",
        therapeutic_area="rare_disease", modality="gene_therapy", stage="phase_1",
        lead_asset="SGT-003 (AAV9 micro-dystrophin, DMD)",
        market_cap_millions=200, cash_millions=100,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.55, strategic_scarcity_score=0.58,
        asset_quality_quick_score=0.48, financing_pressure_score=0.55,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="EDIT", company_id="editas_medicine", asset_id="a-edit",
        company_name="Editas Medicine",
        indication="CRISPR gene editing: sickle cell, LCA10 (retinal)",
        ranking_score=0.42, opportunity_score=0.35, conviction="very-low",
        catalyst="EDIT-301 (SCD/TDT) Phase 1/2 data",
        therapeutic_area="rare_disease", modality="crispr_gene_editing", stage="phase_1",
        lead_asset="EDIT-301 (AsCas12a editing for SCD)",
        market_cap_millions=300, cash_millions=200,
        target_type=TargetType.DISTRESSED, ownership_status="clean",
        mna_relevance_score=0.50, strategic_scarcity_score=0.55,
        asset_quality_quick_score=0.42, financing_pressure_score=0.55,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="PASG", company_id="passage_bio", asset_id="a-pasg",
        company_name="Passage Bio",
        indication="FTD-GRN, GM1 gangliosidosis, Krabbe (CNS gene therapy)",
        ranking_score=0.42, opportunity_score=0.35, conviction="very-low",
        catalyst="PBFT02 (FTD-GRN) Phase 1/2 data",
        therapeutic_area="rare_disease", modality="gene_therapy", stage="phase_1",
        lead_asset="PBFT02 (AAV1 for FTD-GRN)",
        market_cap_millions=200, cash_millions=100,
        target_type=TargetType.DISTRESSED, ownership_status="clean",
        mna_relevance_score=0.48, strategic_scarcity_score=0.52,
        asset_quality_quick_score=0.42, financing_pressure_score=0.60,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="TSHA", company_id="taysha_gene_therapies", asset_id="a-tsha",
        company_name="Taysha Gene Therapies",
        indication="Rett syndrome, SLC13A5 deficiency (CNS AAV gene therapy)",
        ranking_score=0.42, opportunity_score=0.35, conviction="very-low",
        catalyst="TSHA-102 (MECP2 gene therapy, Rett) Phase 1/2 safety data",
        therapeutic_area="rare_disease", modality="gene_therapy", stage="phase_1",
        lead_asset="TSHA-102 (miniMECP2 gene therapy for Rett syndrome)",
        market_cap_millions=200, cash_millions=100,
        target_type=TargetType.DISTRESSED, ownership_status="clean",
        mna_relevance_score=0.48, strategic_scarcity_score=0.52,
        asset_quality_quick_score=0.42, financing_pressure_score=0.62,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="PRQR", company_id="proqr_therapeutics", asset_id="a-prqr",
        company_name="ProQR Therapeutics",
        indication="Leber congenital amaurosis 10, Usher syndrome (RNA editing, oligonucleotides)",
        ranking_score=0.45, opportunity_score=0.38, conviction="low",
        catalyst="Sepofarsen (CEP290/LCA10) Phase 2/3 durability data",
        therapeutic_area="rare_disease", modality="antisense", stage="phase_2",
        lead_asset="sepofarsen (QR-110, RNA editing for LCA10)",
        market_cap_millions=300, cash_millions=150,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.55, strategic_scarcity_score=0.58,
        asset_quality_quick_score=0.45, financing_pressure_score=0.50,
        data_confidence=DataConfidence.LOW,
    ),
]

# ===========================================================================
# Section D — Neuroscience / CNS / psychiatry
# ===========================================================================

CNS_TARGETS: list[WatchlistTarget] = [

    WatchlistTarget(
        ticker="DNLI", company_id="denali_therapeutics", asset_id="a-dnli",
        company_name="Denali Therapeutics",
        indication="Neurodegeneration: LRRK2 (PD), GBA (PD/LSD), ALS, FTD; ETV delivery",
        ranking_score=0.68, opportunity_score=0.62, conviction="medium",
        catalyst="BIIB122 (LRRK2 inhibitor, with Biogen) Phase 2/3 PD data",
        therapeutic_area="neuroscience", modality="small_molecule", stage="phase_2",
        lead_asset="BIIB122 (DNL151, LRRK2 inhibitor for Parkinson's, with Biogen)",
        market_cap_millions=2_000, cash_millions=1_500,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="Biogen (LRRK2, TDP-43); Takeda (ETV platform)",
        mna_relevance_score=0.75, strategic_scarcity_score=0.78,
        asset_quality_quick_score=0.70, financing_pressure_score=0.22,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="PRAX", company_id="praxis_precision_medicine", asset_id="a-prax",
        company_name="Praxis Precision Medicine",
        indication="Epilepsy, essential tremor (GABA and NaV channel modulators)",
        ranking_score=0.65, opportunity_score=0.60, conviction="medium",
        catalyst="PRAX-628 (GABAR) Phase 3 focal epilepsy data; PRAX-562 NaV1.2 data",
        therapeutic_area="neuroscience", modality="small_molecule", stage="phase_3",
        lead_asset="PRAX-628 (GABAR modulator for epilepsy)",
        market_cap_millions=1_500, cash_millions=500,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.72, strategic_scarcity_score=0.72,
        asset_quality_quick_score=0.70, financing_pressure_score=0.28,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="AXSM", company_id="axsome_therapeutics", asset_id="a-axsm",
        company_name="Axsome Therapeutics",
        indication="MDD, agitation (Auvelity approved), migraine (AXS-07), narcolepsy",
        ranking_score=0.62, opportunity_score=0.58, conviction="medium",
        catalyst="AXS-12 (reboxetine, narcolepsy) Phase 3 data",
        therapeutic_area="neuroscience", modality="small_molecule", stage="approved",
        lead_asset="Auvelity (AXS-05, MDD) + Sunosi (solriamfetol)",
        market_cap_millions=3_000, cash_millions=200,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.65, strategic_scarcity_score=0.68,
        asset_quality_quick_score=0.68, financing_pressure_score=0.35,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ACAD", company_id="acadia_pharmaceuticals", asset_id="a-acad",
        company_name="Acadia Pharmaceuticals",
        indication="Parkinson's psychosis, Rett syndrome (Nuplazid, Daybue)",
        ranking_score=0.60, opportunity_score=0.52, conviction="medium",
        catalyst="ACP-204 (Alzheimer's psychosis) Phase 3 data",
        therapeutic_area="neuroscience", modality="small_molecule", stage="approved",
        lead_asset="Nuplazid (pimavanserin, Parkinson's psychosis) + Daybue (Rett)",
        market_cap_millions=2_500, cash_millions=500,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.65, financing_pressure_score=0.30,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="NMRA", company_id="neumora_therapeutics", asset_id="a-nmra",
        company_name="Neumora Therapeutics",
        indication="Major depressive disorder, depression (kappa opioid receptor antagonist)",
        ranking_score=0.60, opportunity_score=0.55, conviction="medium",
        catalyst="navacaprant (NMRA-089) Phase 3 MDD data (KOASTAL-1)",
        therapeutic_area="neuroscience", modality="small_molecule", stage="phase_3",
        lead_asset="navacaprant (NMRA-089, κ-opioid antagonist for MDD)",
        market_cap_millions=800, cash_millions=600,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.65, strategic_scarcity_score=0.68,
        asset_quality_quick_score=0.65, financing_pressure_score=0.28,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="SAGE", company_id="sage_therapeutics", asset_id="a-sage",
        company_name="Sage Therapeutics",
        indication="Postpartum depression, MDD, epilepsy (neuroactive steroids)",
        ranking_score=0.58, opportunity_score=0.52, conviction="medium",
        catalyst="SAGE-324 (essential tremor) Phase 2 data; zuranolone lifecycle expansion",
        therapeutic_area="neuroscience", modality="small_molecule", stage="approved",
        lead_asset="Zurzuvae (zuranolone, approved PPD/MDD with Biogen)",
        market_cap_millions=1_000, cash_millions=600,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="partnered",
        key_partner="Biogen (zuranolone co-promotion and commercialization)",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.62, financing_pressure_score=0.32,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="NGNE", company_id="neurogene", asset_id="a-ngne",
        company_name="Neurogene",
        indication="Rett syndrome, CLN5 Batten disease (CNS gene therapy)",
        ranking_score=0.58, opportunity_score=0.52, conviction="low",
        catalyst="NGN-401 (MECP2, Rett syndrome) Phase 1/2 pediatric data",
        therapeutic_area="neuroscience", modality="gene_therapy", stage="phase_1",
        lead_asset="NGN-401 (miniMECP2 gene therapy for Rett syndrome)",
        market_cap_millions=600, cash_millions=300,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.58, financing_pressure_score=0.38,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="ANNX", company_id="annexon_biosciences", asset_id="a-annx",
        company_name="Annexon Biosciences",
        indication="Guillain-Barré syndrome, Huntington's disease (C1q complement inhibition)",
        ranking_score=0.58, opportunity_score=0.52, conviction="medium",
        catalyst="ANX005 Phase 3 GBS (guillain-barré) data",
        therapeutic_area="neuroscience", modality="monoclonal_antibody", stage="phase_3",
        lead_asset="ANX005 (anti-C1q antibody for GBS)",
        market_cap_millions=400, cash_millions=200,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.60, financing_pressure_score=0.40,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ALKS", company_id="alkermes", asset_id="a-alks",
        company_name="Alkermes",
        indication="CNS/addiction: schizophrenia, MDD, opioid use disorder (LYBALVI, Vivitrol)",
        ranking_score=0.58, opportunity_score=0.50, conviction="medium",
        catalyst="ALKS-2680 (orexin receptor agonist) Phase 2/3 narcolepsy data",
        therapeutic_area="neuroscience", modality="small_molecule", stage="approved",
        lead_asset="LYBALVI (olanzapine/samidorphan) + Vivitrol + ALKS-2680",
        market_cap_millions=3_000, cash_millions=600,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.60,
        asset_quality_quick_score=0.62, financing_pressure_score=0.30,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="VIGL", company_id="vigil_neuroscience", asset_id="a-vigl",
        company_name="Vigil Neuroscience",
        indication="TREM2-mediated neurodegeneration (ALSP, Alzheimer's, Parkinson's)",
        ranking_score=0.55, opportunity_score=0.48, conviction="low",
        catalyst="VGL101 (anti-TREM2 agonist Ab) Phase 1/2 ALSP data",
        therapeutic_area="neuroscience", modality="monoclonal_antibody", stage="phase_1",
        lead_asset="VGL101 (TREM2 agonist for neurodegeneration)",
        market_cap_millions=300, cash_millions=200,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.58, strategic_scarcity_score=0.62,
        asset_quality_quick_score=0.55, financing_pressure_score=0.42,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="PRTA", company_id="prothena", asset_id="a-prta",
        company_name="Prothena",
        indication="AL amyloidosis, Alzheimer's, alpha-synuclein (protein misfolding platform)",
        ranking_score=0.55, opportunity_score=0.48, conviction="medium",
        catalyst="Birtamimab Phase 3 AL amyloidosis (AFFIRM-AL) data",
        therapeutic_area="neuroscience", modality="monoclonal_antibody", stage="phase_3",
        lead_asset="birtamimab (anti-amyloid for AL amyloidosis)",
        market_cap_millions=500, cash_millions=200,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.58, strategic_scarcity_score=0.60,
        asset_quality_quick_score=0.55, financing_pressure_score=0.45,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="OVID", company_id="ovid_therapeutics", asset_id="a-ovid",
        company_name="Ovid Therapeutics",
        indication="Rare CNS: CDKL5 deficiency disorder, Angelman syndrome, Dravet",
        ranking_score=0.48, opportunity_score=0.40, conviction="low",
        catalyst="OV329 (GABA-T inhibitor for CDKL5) Phase 2 data",
        therapeutic_area="neuroscience", modality="small_molecule", stage="phase_2",
        lead_asset="OV329 (GABA transaminase inhibitor for rare epilepsy)",
        market_cap_millions=200, cash_millions=150,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="partnered",
        key_partner="Takeda (soticlestat for Dravet/Angelman)",
        mna_relevance_score=0.52, strategic_scarcity_score=0.55,
        asset_quality_quick_score=0.48, financing_pressure_score=0.50,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="BTAI", company_id="bioxcel_therapeutics", asset_id="a-btai",
        company_name="BioXcel Therapeutics",
        indication="Acute agitation in dementia/schizophrenia (dexmedetomidine sublingual)",
        ranking_score=0.45, opportunity_score=0.38, conviction="low",
        catalyst="IGALMOR (brixia) commercial ramp in dementia agitation",
        therapeutic_area="neuroscience", modality="small_molecule", stage="approved",
        lead_asset="IGALMOR (brixia, sublingual dexmedetomidine for agitation)",
        market_cap_millions=200, cash_millions=50,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.48, strategic_scarcity_score=0.50,
        asset_quality_quick_score=0.45, financing_pressure_score=0.65,
        data_confidence=DataConfidence.MEDIUM,
    ),
]

# Combined for registry import
CORE_TARGETS: list[WatchlistTarget] = (
    IMMUNOLOGY_TARGETS + RARE_DISEASE_TARGETS + CNS_TARGETS
)
