"""Target registry — Cardiometabolic, Hematology, Ophthalmology, Infectious Disease / Vaccines.

Section E: Cardiometabolic / obesity / MASH / renal — 15 companies
Section F: Hematology / complement / immuno-hematology — 15 companies
Section G: Ophthalmology — 7 companies
Section H: Infectious disease / vaccines — 11 companies

Notes:
- Akero Therapeutics (AKRO): ACQUIRED by Novo Nordisk 2026 — in PRECEDENT_REGISTRY
- Avidity Biosciences (RNA): ACQUIRED by Novartis 2026 — in PRECEDENT_REGISTRY
- Calliditas (CALT): ACQUIRED by AstraZeneca 2024 — not in active targets
- CinCor Pharma (CINC): ACQUIRED by AstraZeneca 2023
"""
from __future__ import annotations

from bve.entities.target import (
    WatchlistTarget, TargetType, DataConfidence,
)

# ===========================================================================
# Section E — Cardiometabolic / obesity / MASH / renal
# ===========================================================================

CARDIOMETABOLIC_TARGETS: list[WatchlistTarget] = [

    WatchlistTarget(
        ticker="VKTX", company_id="viking_therapeutics", asset_id="a-vktx",
        company_name="Viking Therapeutics",
        indication="Obesity, MASH (dual GLP-1/GIP agonist, oral + injectable)",
        ranking_score=0.78, opportunity_score=0.75, conviction="medium",
        catalyst="VK2735 oral obesity Phase 2 data; VK2735 injectable Phase 3 start",
        therapeutic_area="cardiometabolic", modality="small_molecule", stage="phase_2",
        lead_asset="VK2735 (dual GLP-1/GIP agonist, oral and injectable)",
        market_cap_millions=4_000, cash_millions=900,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.85, strategic_scarcity_score=0.88,
        asset_quality_quick_score=0.82, financing_pressure_score=0.20,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="MDGL", company_id="madrigal", asset_id="a-mdgl",
        company_name="Madrigal Pharmaceuticals",
        indication="MASH (metabolic dysfunction-associated steatohepatitis) — first approved drug",
        ranking_score=0.72, opportunity_score=0.68, conviction="medium",
        catalyst="Rezdiffra commercial ramp; Phase 4 outcomes data",
        therapeutic_area="cardiometabolic", modality="small_molecule", stage="approved",
        lead_asset="Rezdiffra (resmetirom, THRβ agonist — first MASH approval)",
        market_cap_millions=6_000, cash_millions=1_000,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.78, strategic_scarcity_score=0.82,
        asset_quality_quick_score=0.80, financing_pressure_score=0.22,
        data_confidence=DataConfidence.HIGH,
    ),

    WatchlistTarget(
        ticker="EWTX", company_id="edgewise_therapeutics", asset_id="a-ewtx",
        company_name="Edgewise Therapeutics",
        indication="HCM, skeletal muscle disorders (cardiac myosin modulators)",
        ranking_score=0.68, opportunity_score=0.62, conviction="medium",
        catalyst="EDG-7500 Phase 2 HCM data",
        therapeutic_area="cardiometabolic", modality="small_molecule", stage="phase_2",
        lead_asset="EDG-7500 (cardiac myosin modulator for HCM)",
        market_cap_millions=1_000, cash_millions=400,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.72, strategic_scarcity_score=0.75,
        asset_quality_quick_score=0.70, financing_pressure_score=0.30,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="CRNX", company_id="crinetics", asset_id="a-crnx",
        company_name="Crinetics Pharmaceuticals",
        indication="Acromegaly, Cushing's, carcinoid (oral somatostatin agonist + MC4R)",
        ranking_score=0.68, opportunity_score=0.62, conviction="medium",
        catalyst="paltusotine Phase 3 acromegaly NDA; atumelnant Phase 2 Prader-Willi",
        therapeutic_area="cardiometabolic", modality="small_molecule", stage="phase_3",
        lead_asset="paltusotine (oral somatostatin agonist for acromegaly)",
        market_cap_millions=2_500, cash_millions=600,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.72, strategic_scarcity_score=0.75,
        asset_quality_quick_score=0.72, financing_pressure_score=0.25,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ZEAL", company_id="zealand_pharma", asset_id="a-zeal",
        company_name="Zealand Pharma",
        indication="Obesity, short bowel syndrome, hypoglycemia (peptide platform)",
        ranking_score=0.68, opportunity_score=0.62, conviction="medium",
        catalyst="bomacopatide (GIP/GLP-1/GCG triagonist) Phase 2 obesity data",
        therapeutic_area="cardiometabolic", modality="peptide", stage="phase_2",
        lead_asset="bomacopatide (GIP/GLP-1/GCG tri-agonist for obesity)",
        market_cap_millions=3_000, cash_millions=500,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.72, strategic_scarcity_score=0.75,
        asset_quality_quick_score=0.72, financing_pressure_score=0.28,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="GPCR", company_id="structure_therapeutics_cardio", asset_id="a-gpcr-cardio",
        company_name="Structure Therapeutics",
        indication="Obesity, type 2 diabetes (oral GLP-1R agonist)",
        ranking_score=0.70, opportunity_score=0.68, conviction="medium",
        catalyst="GSBR-1290 Phase 2/3 obesity/T2D data",
        therapeutic_area="cardiometabolic", modality="small_molecule", stage="phase_2",
        lead_asset="GSBR-1290 (oral GLP-1R agonist)",
        market_cap_millions=1_500, cash_millions=500,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.80, strategic_scarcity_score=0.82,
        asset_quality_quick_score=0.75, financing_pressure_score=0.28,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ARWR", company_id="arrowhead_pharma", asset_id="a-arwr",
        company_name="Arrowhead Pharmaceuticals",
        indication="Cardiometabolic, liver disease (RNAi platform: ANGPTL3, APOC3, PCSK9)",
        ranking_score=0.65, opportunity_score=0.60, conviction="medium",
        catalyst="ARO-ANG3 (ANGPTL3 siRNA) Phase 3 HoFH/HTG data; plozasiran FDA review",
        therapeutic_area="cardiometabolic", modality="rnai", stage="phase_3",
        lead_asset="plozasiran (ARO-APOC3, for severe hypertriglyceridemia) — Pfizer partnership",
        market_cap_millions=2_500, cash_millions=400,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="Pfizer (plozasiran/ARO-APOC3), GSK (ARO-HSD liver)",
        mna_relevance_score=0.75, strategic_scarcity_score=0.78,
        asset_quality_quick_score=0.72, financing_pressure_score=0.32,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="RYTM", company_id="rhythm_pharma", asset_id="a-rytm",
        company_name="Rhythm Pharmaceuticals",
        indication="Rare monogenic obesity (POMC, PCSK1, LEPR deficiency)",
        ranking_score=0.62, opportunity_score=0.58, conviction="medium",
        catalyst="Imcivree label expansion to additional MC4R pathway disorders",
        therapeutic_area="cardiometabolic", modality="biologic", stage="approved",
        lead_asset="Imcivree (setmelanotide, MC4R agonist for rare obesity)",
        market_cap_millions=1_500, cash_millions=400,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.68, strategic_scarcity_score=0.72,
        asset_quality_quick_score=0.68, financing_pressure_score=0.30,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="MLYS", company_id="mineralys", asset_id="a-mlys",
        company_name="Mineralys Therapeutics",
        indication="Uncontrolled hypertension, primary aldosteronism (CYP11B2 inhibitor)",
        ranking_score=0.60, opportunity_score=0.55, conviction="medium",
        catalyst="lorundrostat Phase 3 hypertension (TARGET-HTN) primary endpoint",
        therapeutic_area="cardiometabolic", modality="small_molecule", stage="phase_3",
        lead_asset="lorundrostat (aldosterone synthase inhibitor for hypertension)",
        market_cap_millions=800, cash_millions=400,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.68, strategic_scarcity_score=0.70,
        asset_quality_quick_score=0.65, financing_pressure_score=0.32,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ETNB", company_id="89bio", asset_id="a-etnb",
        company_name="89bio",
        indication="MASH, severe hypertriglyceridemia (FGF21 analog)",
        ranking_score=0.60, opportunity_score=0.55, conviction="medium",
        catalyst="pegozafermin Phase 3 MASH (ENTRUST) primary endpoint data",
        therapeutic_area="cardiometabolic", modality="biologic", stage="phase_3",
        lead_asset="pegozafermin (FGF21 analog for MASH and SHTG)",
        market_cap_millions=800, cash_millions=400,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.68, strategic_scarcity_score=0.70,
        asset_quality_quick_score=0.65, financing_pressure_score=0.35,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="CORT", company_id="corcept_therapeutics", asset_id="a-cort",
        company_name="Corcept Therapeutics",
        indication="Cushing's syndrome, endometriosis, TNBC (GR modulation)",
        ranking_score=0.60, opportunity_score=0.52, conviction="medium",
        catalyst="Relacorilant Phase 3 Cushing's NDA; endometriosis data",
        therapeutic_area="cardiometabolic", modality="small_molecule", stage="approved",
        lead_asset="Korlym (mifepristone) + relacorilant (next-gen GR modulator)",
        market_cap_millions=3_000, cash_millions=400,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.65, financing_pressure_score=0.25,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ALT", company_id="altimmune", asset_id="a-alt",
        company_name="Altimmune",
        indication="Obesity, MASH (dual GLP-1/glucagon agonist)",
        ranking_score=0.58, opportunity_score=0.52, conviction="low",
        catalyst="pemvidutide Phase 2 MASH (MOMENTUM) histology data",
        therapeutic_area="cardiometabolic", modality="peptide", stage="phase_2",
        lead_asset="pemvidutide (GLP-1/glucagon dual agonist for obesity/MASH)",
        market_cap_millions=600, cash_millions=200,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.60, financing_pressure_score=0.40,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="TERN", company_id="terns_pharma", asset_id="a-tern",
        company_name="Terns Pharmaceuticals",
        indication="MASH, obesity (THRβ agonist + oral GLP-1 combination)",
        ranking_score=0.55, opportunity_score=0.50, conviction="low",
        catalyst="TERN-501 Phase 2 MASH data; TERN-701 Phase 1 obesity data",
        therapeutic_area="cardiometabolic", modality="small_molecule", stage="phase_2",
        lead_asset="TERN-501 (THRβ agonist for MASH)",
        market_cap_millions=600, cash_millions=300,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.58, financing_pressure_score=0.38,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="TNYA", company_id="tenaya_therapeutics", asset_id="a-tnya",
        company_name="Tenaya Therapeutics",
        indication="Hypertrophic cardiomyopathy, arrhythmogenic cardiomyopathy (cardiac gene therapy)",
        ranking_score=0.52, opportunity_score=0.45, conviction="low",
        catalyst="TN-201 (PKP2-ACM) Phase 1 safety data",
        therapeutic_area="cardiometabolic", modality="gene_therapy", stage="phase_1",
        lead_asset="TN-401 (MYBPC3 for HCM); TN-201 (PKP2 for ACM)",
        market_cap_millions=200, cash_millions=100,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.58, strategic_scarcity_score=0.62,
        asset_quality_quick_score=0.52, financing_pressure_score=0.55,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="SGMT", company_id="sagimet", asset_id="a-sgmt",
        company_name="Sagimet Biosciences",
        indication="MASH (FASN inhibitor)",
        ranking_score=0.35, opportunity_score=0.28, conviction="very-low",
        catalyst="denifanstat Phase 2 MASH data",
        therapeutic_area="cardiometabolic", modality="small_molecule", stage="phase_2",
        lead_asset="denifanstat (FASN inhibitor for MASH)",
        market_cap_millions=100, cash_millions=60,
        target_type=TargetType.DISTRESSED, ownership_status="clean",
        mna_relevance_score=0.35, strategic_scarcity_score=0.40,
        asset_quality_quick_score=0.35, financing_pressure_score=0.72,
        data_confidence=DataConfidence.LOW,
    ),
]

# ===========================================================================
# Section F — Hematology / complement / immuno-hematology
# ===========================================================================

HEMATOLOGY_TARGETS: list[WatchlistTarget] = [

    WatchlistTarget(
        ticker="ACLX", company_id="arcellx", asset_id="a-aclx",
        company_name="Arcellx",
        indication="Multiple myeloma (BCMA CAR-T, next-gen CAR constructs)",
        ranking_score=0.72, opportunity_score=0.68, conviction="medium",
        catalyst="Anito-cel BLA decision; anito-cel vs KarMMa/Carvykti data",
        therapeutic_area="hematology", modality="cell_therapy", stage="approved",
        lead_asset="anito-cel (CART-ddBCMA, with Gilead/Kite) — BLA submitted",
        market_cap_millions=3_000, cash_millions=700,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="Gilead Sciences / Kite (anito-cel commercialization)",
        mna_relevance_score=0.78, strategic_scarcity_score=0.80,
        asset_quality_quick_score=0.78, financing_pressure_score=0.25,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="APLS", company_id="apellis", asset_id="a-apls",
        company_name="Apellis Pharmaceuticals",
        indication="Geographic atrophy, PNH, complement-mediated rare diseases",
        ranking_score=0.68, opportunity_score=0.62, conviction="medium",
        catalyst="Systemic C3 inhibitor programs; Syfovre year 2 commercial data",
        therapeutic_area="hematology", modality="small_molecule", stage="approved",
        lead_asset="Syfovre (pegcetacoplan, C3 inhibitor for GA — first approved GA therapy)",
        market_cap_millions=3_000, cash_millions=700,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.72, strategic_scarcity_score=0.75,
        asset_quality_quick_score=0.72, financing_pressure_score=0.28,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="BPMC", company_id="blueprint_medicines", asset_id="a-bpmc",
        company_name="Blueprint Medicines",
        indication="Systemic mastocytosis, GIST, CMML (KIT/PDGFRA precision oncology)",
        ranking_score=0.65, opportunity_score=0.60, conviction="medium",
        catalyst="elenestinib Phase 2 non-advanced SM data; BLU-808 (TIM-3) CMML data",
        therapeutic_area="hematology", modality="small_molecule", stage="approved",
        lead_asset="Ayvakit (avapritinib, KIT D816V for SM) + elenestinib",
        market_cap_millions=3_500, cash_millions=1_000,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.70, strategic_scarcity_score=0.72,
        asset_quality_quick_score=0.72, financing_pressure_score=0.25,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="AGIO", company_id="agios_pharmaceuticals", asset_id="a-agio",
        company_name="Agios Pharmaceuticals",
        indication="Thalassemia, PK deficiency, sickle cell (mitochondrial metabolism)",
        ranking_score=0.62, opportunity_score=0.55, conviction="medium",
        catalyst="Pyrukynd Phase 3 non-TDT beta-thalassemia data",
        therapeutic_area="hematology", modality="small_molecule", stage="approved",
        lead_asset="Pyrukynd (mitapivat, PK activator for hemolytic anemias)",
        market_cap_millions=2_000, cash_millions=700,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.68, strategic_scarcity_score=0.70,
        asset_quality_quick_score=0.68, financing_pressure_score=0.28,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="GERN", company_id="geron", asset_id="a-gern",
        company_name="Geron Corporation",
        indication="Lower-risk MDS (myelodysplastic syndrome) — telomerase inhibitor",
        ranking_score=0.60, opportunity_score=0.52, conviction="medium",
        catalyst="Rytelo commercial uptake; Phase 3 label expansion to higher-risk MDS",
        therapeutic_area="hematology", modality="oligonucleotide", stage="approved",
        lead_asset="Rytelo (imetelstat, telomerase inhibitor for low-risk MDS)",
        market_cap_millions=800, cash_millions=300,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.62, financing_pressure_score=0.38,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="IRON", company_id="disc_medicine", asset_id="a-iron",
        company_name="Disc Medicine",
        indication="Polycythemia vera, myelofibrosis, IDA (erythropoiesis regulation via hepcidin)",
        ranking_score=0.60, opportunity_score=0.55, conviction="medium",
        catalyst="bitopertin Phase 2 EPP data; DISC-0974 Phase 2 anemia data",
        therapeutic_area="hematology", modality="small_molecule", stage="phase_2",
        lead_asset="bitopertin (GlyT1 inhibitor for erythropoietic protoporphyria)",
        market_cap_millions=1_000, cash_millions=400,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.65, strategic_scarcity_score=0.68,
        asset_quality_quick_score=0.62, financing_pressure_score=0.35,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ATXS", company_id="astria_therapeutics", asset_id="a-atxs",
        company_name="Astria Therapeutics",
        indication="Hereditary angioedema (anti-plasma kallikrein antibody)",
        ranking_score=0.60, opportunity_score=0.55, conviction="medium",
        catalyst="STAR-0215 (anti-kallikrein mAb) Phase 2/3 HAE prophylaxis data",
        therapeutic_area="hematology", modality="monoclonal_antibody", stage="phase_2",
        lead_asset="STAR-0215 (anti-plasma kallikrein mAb for HAE)",
        market_cap_millions=600, cash_millions=300,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.65, strategic_scarcity_score=0.68,
        asset_quality_quick_score=0.62, financing_pressure_score=0.35,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="FULC", company_id="fulcrum_therapeutics", asset_id="a-fulc",
        company_name="Fulcrum Therapeutics",
        indication="Sickle cell disease, facioscapulohumeral dystrophy (HbF induction)",
        ranking_score=0.58, opportunity_score=0.52, conviction="medium",
        catalyst="pociredir Phase 2 SCD data (HbF inducer via BCL11A repression)",
        therapeutic_area="hematology", modality="small_molecule", stage="phase_2",
        lead_asset="pociredir (FTX-6058, BCL11A repressor → HbF inducer for SCD)",
        market_cap_millions=500, cash_millions=200,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.60, financing_pressure_score=0.42,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="AUTL", company_id="autolus", asset_id="a-autl",
        company_name="Autolus Therapeutics",
        indication="B-ALL, DLBCL (CD19 CAR-T; FASTCAR manufacturing)",
        ranking_score=0.58, opportunity_score=0.52, conviction="medium",
        catalyst="Obe-cel (obecabtagene autoleucel) B-ALL commercial launch",
        therapeutic_area="hematology", modality="cell_therapy", stage="approved",
        lead_asset="obecabtagene autoleucel (obe-cel, fast-off CD19 CAR-T for B-ALL)",
        market_cap_millions=400, cash_millions=200,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.60, financing_pressure_score=0.45,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="KALV", company_id="kalvista", asset_id="a-kalv",
        company_name="KalVista Pharmaceuticals",
        indication="Hereditary angioedema (oral plasma kallikrein inhibitor)",
        ranking_score=0.58, opportunity_score=0.52, conviction="medium",
        catalyst="sebetralstat Phase 3 HAE data (vs standard of care)",
        therapeutic_area="hematology", modality="small_molecule", stage="phase_3",
        lead_asset="sebetralstat (oral plasma kallikrein inhibitor for HAE on-demand)",
        market_cap_millions=300, cash_millions=150,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.60, financing_pressure_score=0.42,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ALLO", company_id="allogene", asset_id="a-allo",
        company_name="Allogene Therapeutics",
        indication="B-cell malignancies (allogeneic off-the-shelf CAR-T)",
        ranking_score=0.55, opportunity_score=0.48, conviction="low",
        catalyst="ALLO-501A Phase 2 r/r LBCL data; ALLO-329 Phase 1 data",
        therapeutic_area="hematology", modality="cell_therapy", stage="phase_2",
        lead_asset="ALLO-501A (allogeneic anti-CD19 CAR-T)",
        market_cap_millions=600, cash_millions=400,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.60, strategic_scarcity_score=0.62,
        asset_quality_quick_score=0.55, financing_pressure_score=0.40,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="PHVS", company_id="pharvaris", asset_id="a-phvs",
        company_name="Pharvaris",
        indication="Hereditary angioedema (oral bradykinin B2 receptor antagonist)",
        ranking_score=0.55, opportunity_score=0.50, conviction="low",
        catalyst="deucrictibant Phase 3 HAE on-demand and prophylaxis data",
        therapeutic_area="hematology", modality="small_molecule", stage="phase_3",
        lead_asset="deucrictibant (PHVS416, oral B2 receptor antagonist for HAE)",
        market_cap_millions=300, cash_millions=150,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.60, strategic_scarcity_score=0.62,
        asset_quality_quick_score=0.58, financing_pressure_score=0.42,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="CRGX", company_id="cargo_therapeutics", asset_id="a-crgx",
        company_name="CARGO Therapeutics",
        indication="Large B-cell lymphoma (CD22 CAR-T; anti-CD19/CD22)",
        ranking_score=0.52, opportunity_score=0.45, conviction="low",
        catalyst="CRG-022 Phase 2 r/r LBCL data",
        therapeutic_area="hematology", modality="cell_therapy", stage="phase_2",
        lead_asset="CRG-022 (anti-CD22 CAR-T for LBCL)",
        market_cap_millions=400, cash_millions=300,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.58, strategic_scarcity_score=0.60,
        asset_quality_quick_score=0.52, financing_pressure_score=0.40,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="FATE", company_id="fate_therapeutics", asset_id="a-fate",
        company_name="Fate Therapeutics",
        indication="Hematologic malignancies (iPSC-derived NK and CAR-NK cells)",
        ranking_score=0.50, opportunity_score=0.42, conviction="low",
        catalyst="FT576 (BCMA/CD16A iPSC-NK) Phase 1 myeloma data",
        therapeutic_area="hematology", modality="cell_therapy", stage="phase_1",
        lead_asset="FT576 (iPSC-derived NK cell for multiple myeloma)",
        market_cap_millions=500, cash_millions=400,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.55, strategic_scarcity_score=0.58,
        asset_quality_quick_score=0.50, financing_pressure_score=0.42,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="NKTX", company_id="nkarta", asset_id="a-nktx",
        company_name="Nkarta",
        indication="AML, myeloma (NKG2D CAR-NK cell therapy)",
        ranking_score=0.45, opportunity_score=0.38, conviction="low",
        catalyst="NKX101 (NKG2D CAR-NK) Phase 1 AML efficacy data",
        therapeutic_area="hematology", modality="cell_therapy", stage="phase_1",
        lead_asset="NKX101 (NKG2D CAR-NK for AML)",
        market_cap_millions=200, cash_millions=100,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.48, strategic_scarcity_score=0.52,
        asset_quality_quick_score=0.45, financing_pressure_score=0.58,
        data_confidence=DataConfidence.LOW,
    ),
]

# ===========================================================================
# Section G — Ophthalmology
# ===========================================================================

OPHTHALMOLOGY_TARGETS: list[WatchlistTarget] = [

    WatchlistTarget(
        ticker="OCUL", company_id="ocular_therapeutix", asset_id="a-ocul",
        company_name="Ocular Therapeutix",
        indication="Wet AMD, DR, dry eye (sustained-release intravitreal drug delivery)",
        ranking_score=0.60, opportunity_score=0.55, conviction="medium",
        catalyst="OTX-TKI (intravitreal tyrosine kinase inhibitor for wet AMD) Phase 2 data",
        therapeutic_area="ophthalmology", modality="small_molecule", stage="phase_2",
        lead_asset="OTX-TKI (sustained-release anti-VEGF TKI for wet AMD)",
        market_cap_millions=700, cash_millions=200,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.62, financing_pressure_score=0.42,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ADVM", company_id="adverum", asset_id="a-advm",
        company_name="Adverum Biotechnologies",
        indication="Wet AMD (intravitreal aflibercept gene therapy — one-time dosing)",
        ranking_score=0.58, opportunity_score=0.52, conviction="medium",
        catalyst="ADVM-022 Phase 2/3 (LUNA) wet AMD data vs injections",
        therapeutic_area="ophthalmology", modality="gene_therapy", stage="phase_2",
        lead_asset="ADVM-022 (intravitreal aflibercept gene therapy for wet AMD)",
        market_cap_millions=400, cash_millions=150,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.60, financing_pressure_score=0.45,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="KOD", company_id="kodiak_sciences", asset_id="a-kod",
        company_name="Kodiak Sciences",
        indication="Retinal vascular diseases: wet AMD, DME, BRVO (anti-VEGF ABC platform)",
        ranking_score=0.55, opportunity_score=0.48, conviction="low",
        catalyst="KSI-301 (anti-VEGF ABC) Phase 2b/3 wet AMD data",
        therapeutic_area="ophthalmology", modality="biologic", stage="phase_2",
        lead_asset="KSI-301 (anti-VEGF antibody biopolymer conjugate)",
        market_cap_millions=300, cash_millions=200,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.58, strategic_scarcity_score=0.60,
        asset_quality_quick_score=0.55, financing_pressure_score=0.42,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="EYPT", company_id="eyepoint_pharma", asset_id="a-eypt",
        company_name="EyePoint Pharmaceuticals",
        indication="Wet AMD, diabetic retinopathy (sustained-release intravitreal vorolanib)",
        ranking_score=0.55, opportunity_score=0.50, conviction="low",
        catalyst="EYP-1901 (intravitreal vorolanib) Phase 2 wet AMD DAVIO data",
        therapeutic_area="ophthalmology", modality="small_molecule", stage="phase_2",
        lead_asset="EYP-1901 (vorolanib intravitreal insert for wet AMD)",
        market_cap_millions=300, cash_millions=150,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.58, strategic_scarcity_score=0.60,
        asset_quality_quick_score=0.55, financing_pressure_score=0.45,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ALDX", company_id="aldeyra", asset_id="a-aldx",
        company_name="Aldeyra Therapeutics",
        indication="Dry eye disease, non-infectious anterior uveitis (RASP modulation)",
        ranking_score=0.48, opportunity_score=0.40, conviction="low",
        catalyst="Reproxalap (RASP modulator) NDA re-submission data",
        therapeutic_area="ophthalmology", modality="small_molecule", stage="phase_3",
        lead_asset="reproxalap (aldehyde modulation for dry eye disease)",
        market_cap_millions=200, cash_millions=100,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.50, strategic_scarcity_score=0.55,
        asset_quality_quick_score=0.48, financing_pressure_score=0.55,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="OCUP", company_id="ocuphire_pharma", asset_id="a-ocup",
        company_name="Ocuphire Pharma",
        indication="Myopia, pupil dilation (phentolamine ophthalmic solution)",
        ranking_score=0.35, opportunity_score=0.28, conviction="very-low",
        catalyst="Nyxol commercial uptake (phentolamine for pharmacologically dilated pupils)",
        therapeutic_area="ophthalmology", modality="small_molecule", stage="approved",
        lead_asset="Nyxol (phentolamine ophthalmic solution 0.75%)",
        market_cap_millions=50, cash_millions=20,
        target_type=TargetType.DISTRESSED, ownership_status="clean",
        mna_relevance_score=0.32, strategic_scarcity_score=0.35,
        asset_quality_quick_score=0.35, financing_pressure_score=0.80,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="RGNX", company_id="regenxbio_ophtho", asset_id="a-rgnx-ophtho",
        company_name="REGENXBIO (ophthalmology programs)",
        indication="Wet AMD, X-linked retinoschisis (AAV retinal gene therapy)",
        ranking_score=0.60, opportunity_score=0.55, conviction="medium",
        catalyst="RGX-314 (wet AMD gene therapy, with AbbVie) Phase 3 ATMOSPHERE data",
        therapeutic_area="ophthalmology", modality="gene_therapy", stage="phase_3",
        lead_asset="RGX-314 (AAV8 anti-VEGF for wet AMD, with AbbVie)",
        market_cap_millions=800, cash_millions=400,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="AbbVie (RGX-314 subretinal and suprachoroidal)",
        mna_relevance_score=0.65, strategic_scarcity_score=0.68,
        asset_quality_quick_score=0.62, financing_pressure_score=0.38,
        data_confidence=DataConfidence.MEDIUM,
    ),
]

# ===========================================================================
# Section H — Infectious disease / vaccines
# ===========================================================================

INFECTIOUS_DISEASE_TARGETS: list[WatchlistTarget] = [

    WatchlistTarget(
        ticker="DVAX", company_id="dynavax", asset_id="a-dvax",
        company_name="Dynavax Technologies",
        indication="HBV vaccines, CpG adjuvant platform (HEPLISAV-B approved)",
        ranking_score=0.65, opportunity_score=0.62, conviction="medium",
        catalyst="HEPLISAV-B market share growth; CpG adjuvant partnerships for new vaccines",
        therapeutic_area="infectious_disease", modality="vaccine", stage="approved",
        lead_asset="HEPLISAV-B (CpG1018-adjuvanted HBV vaccine) + CpG adjuvant platform",
        market_cap_millions=1_500, cash_millions=400,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.68, strategic_scarcity_score=0.72,
        asset_quality_quick_score=0.68, financing_pressure_score=0.28,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="VIR", company_id="vir_biotechnology", asset_id="a-vir",
        company_name="Vir Biotechnology",
        indication="Chronic HBV, HDV (antibody + siRNA combination approach)",
        ranking_score=0.62, opportunity_score=0.55, conviction="medium",
        catalyst="VIR-3434 + elebsiran Phase 3 HBV functional cure data",
        therapeutic_area="infectious_disease", modality="monoclonal_antibody", stage="phase_3",
        lead_asset="tobevibart + elebsiran (HBsAg mAb + RNAi for HBV cure)",
        market_cap_millions=800, cash_millions=600,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="partnered",
        key_partner="GSK (VIR-7831 sotrovimab, legacy; HBV collaboration)",
        mna_relevance_score=0.65, strategic_scarcity_score=0.68,
        asset_quality_quick_score=0.65, financing_pressure_score=0.32,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ARCT", company_id="arcturus_therapeutics", asset_id="a-arct",
        company_name="Arcturus Therapeutics",
        indication="Respiratory infections, rare disease (self-amplifying mRNA platform)",
        ranking_score=0.60, opportunity_score=0.52, conviction="medium",
        catalyst="ARCT-154 (COVID saRNA) Japan approval; ARCT-2304 (mRNA RSV) Phase 2",
        therapeutic_area="infectious_disease", modality="mrna", stage="approved",
        lead_asset="ARCT-154 (COVID-19 self-amplifying mRNA, Japan approved 2023)",
        market_cap_millions=800, cash_millions=400,
        target_type=TargetType.PLATFORM, ownership_status="clean",
        mna_relevance_score=0.62, strategic_scarcity_score=0.65,
        asset_quality_quick_score=0.62, financing_pressure_score=0.38,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="NVAX", company_id="novavax", asset_id="a-nvax",
        company_name="Novavax",
        indication="COVID-19, influenza, respiratory vaccines (protein subunit + Matrix-M adjuvant)",
        ranking_score=0.52, opportunity_score=0.45, conviction="low",
        catalyst="NVX-CoV2601 XBB.1.5 commercial; flu + COVID combo trial data",
        therapeutic_area="infectious_disease", modality="vaccine", stage="approved",
        lead_asset="Nuvaxovid (COVID-19 protein subunit) + Matrix-M adjuvant",
        market_cap_millions=1_000, cash_millions=300,
        target_type=TargetType.PLATFORM, ownership_status="partnered",
        key_partner="Sanofi ($1.2B deal 2024; global commercialization partnership)",
        mna_relevance_score=0.55, strategic_scarcity_score=0.60,
        asset_quality_quick_score=0.52, financing_pressure_score=0.50,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="VALN", company_id="valneva", asset_id="a-valn",
        company_name="Valneva",
        indication="Chikungunya, Lyme disease, VLA1553 (inactivated Chikungunya vaccine)",
        ranking_score=0.55, opportunity_score=0.48, conviction="low",
        catalyst="IXCHIQ US commercial ramp; VLA15 (Lyme) Phase 3 data with Pfizer",
        therapeutic_area="infectious_disease", modality="vaccine", stage="approved",
        lead_asset="IXCHIQ (VLA1553, chikungunya live-attenuated vaccine — approved 2023)",
        market_cap_millions=300, cash_millions=200,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="partnered",
        key_partner="Pfizer (VLA15 Lyme disease Phase 3 co-development)",
        mna_relevance_score=0.58, strategic_scarcity_score=0.60,
        asset_quality_quick_score=0.58, financing_pressure_score=0.42,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ABUS", company_id="arbutus_biopharma", asset_id="a-abus",
        company_name="Arbutus Biopharma",
        indication="Chronic HBV (oral PD-L1 inhibitor + HBV combination approach)",
        ranking_score=0.52, opportunity_score=0.45, conviction="low",
        catalyst="AB-101 (oral PD-L1 inhibitor) Phase 1 HBV data; LNP IP royalty outcomes",
        therapeutic_area="infectious_disease", modality="small_molecule", stage="phase_1",
        lead_asset="AB-101 (oral PD-L1 inhibitor for HBV functional cure)",
        market_cap_millions=300, cash_millions=100,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.55, strategic_scarcity_score=0.58,
        asset_quality_quick_score=0.52, financing_pressure_score=0.55,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="CDTX", company_id="cidara_therapeutics", asset_id="a-cdtx",
        company_name="Cidara Therapeutics",
        indication="Invasive fungal infections (echinocandin antifungal — once weekly)",
        ranking_score=0.50, opportunity_score=0.42, conviction="low",
        catalyst="Rezzayo commercial ramp; CD388 (MDSC, anti-influenza CD16A/HA) Phase 1",
        therapeutic_area="infectious_disease", modality="small_molecule", stage="approved",
        lead_asset="Rezzayo (rezafungin, once-weekly echinocandin — approved 2023)",
        market_cap_millions=200, cash_millions=100,
        target_type=TargetType.COMMERCIAL_FRANCHISE, ownership_status="clean",
        mna_relevance_score=0.52, strategic_scarcity_score=0.55,
        asset_quality_quick_score=0.50, financing_pressure_score=0.55,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="ASMB", company_id="assembly_bio", asset_id="a-asmb",
        company_name="Assembly Biosciences",
        indication="Chronic HBV (nucleocapsid assembly modulators + combination)",
        ranking_score=0.45, opportunity_score=0.38, conviction="low",
        catalyst="ABI-H0731 + NrtI combination Phase 2 HBV virologic response data",
        therapeutic_area="infectious_disease", modality="small_molecule", stage="phase_2",
        lead_asset="ABI-H0731 (HBV core inhibitor / capsid assembly modulator)",
        market_cap_millions=200, cash_millions=100,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.48, strategic_scarcity_score=0.52,
        asset_quality_quick_score=0.45, financing_pressure_score=0.60,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="ENTA", company_id="enanta_pharma", asset_id="a-enta",
        company_name="Enanta Pharmaceuticals",
        indication="RSV, HBV, COVID-19 (small molecule antivirals)",
        ranking_score=0.45, opportunity_score=0.38, conviction="low",
        catalyst="EDP-938 (RSV N-protein inhibitor) Phase 2/3 data",
        therapeutic_area="infectious_disease", modality="small_molecule", stage="phase_2",
        lead_asset="EDP-938 (RSV replication inhibitor)",
        market_cap_millions=300, cash_millions=300,
        target_type=TargetType.PIPELINE_PORTFOLIO, ownership_status="clean",
        mna_relevance_score=0.48, strategic_scarcity_score=0.52,
        asset_quality_quick_score=0.45, financing_pressure_score=0.38,
        data_confidence=DataConfidence.MEDIUM,
    ),

    WatchlistTarget(
        ticker="HLVX", company_id="hillevax", asset_id="a-hlvx",
        company_name="HilleVax",
        indication="Norovirus (VLP-based vaccine)",
        ranking_score=0.40, opportunity_score=0.32, conviction="very-low",
        catalyst="HIL-214 norovirus VLP Phase 2b data; partnership discussions",
        therapeutic_area="infectious_disease", modality="vaccine", stage="phase_2",
        lead_asset="HIL-214 (norovirus bivalent VLP vaccine)",
        market_cap_millions=300, cash_millions=200,
        target_type=TargetType.SINGLE_ASSET, ownership_status="clean",
        mna_relevance_score=0.42, strategic_scarcity_score=0.48,
        asset_quality_quick_score=0.40, financing_pressure_score=0.45,
        data_confidence=DataConfidence.LOW,
    ),

    WatchlistTarget(
        ticker="AVIR", company_id="atea_pharma", asset_id="a-avir",
        company_name="Atea Pharmaceuticals",
        indication="HCV, COVID-19 antivirals (nucleotide analog)",
        ranking_score=0.35, opportunity_score=0.28, conviction="very-low",
        catalyst="AT-527 (COVID) salvage partnership; HCV program partnership",
        therapeutic_area="infectious_disease", modality="small_molecule", stage="phase_2",
        lead_asset="AT-527 (purine nucleotide analog antiviral)",
        market_cap_millions=200, cash_millions=200,
        target_type=TargetType.DISTRESSED, ownership_status="clean",
        mna_relevance_score=0.38, strategic_scarcity_score=0.42,
        asset_quality_quick_score=0.35, financing_pressure_score=0.50,
        data_confidence=DataConfidence.LOW,
    ),
]

# Combined for registry import
OTHER_TARGETS: list[WatchlistTarget] = (
    CARDIOMETABOLIC_TARGETS + HEMATOLOGY_TARGETS
    + OPHTHALMOLOGY_TARGETS + INFECTIOUS_DISEASE_TARGETS
)
